### ISSUE TITLE
365 Transposed

### ISSUE THREAD

**Issue by JCSchJ** [MicrosoftDocs/data-integration#1]
This looks incorrect near the top of the page -&gt;Office 356 tenant, yes?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2a07eaa-023b-fbc8-9508-39411425d096
* Version Independent ID: efb6bb0e-5551-e2b3-4e98-3a34188600f3
* Content: [Set the data center region for the on-premises data gateway](https://docs.microsoft.com/en-us/data-integration/gateway/service-gateway-data-region#feedback)
* Content Source: [data-integration/gateway/service-gateway-data-region.md](https://github.com/MicrosoftDocs/data-integration/blob/master/data-integration/gateway/service-gateway-data-region.md)
* Service: **powerbi**
* Sub-service: **powerbi-gateways**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by mgblythe** [comment]
Thanks for catching that issue, @JCSchJ! Fixing now

For future reference - you can also edit articles directly. Click the little Edit pencil icon in the article, then click the little Edit pencil in GitHub, make your change, scroll to the bottom, and click Propose file change. And voila! It's sent directly to the writer, who will sign off and get it published. Thanks again!

**Comment by mgblythe** [comment]
Fix verified.

**Comment by JCSchJ** [comment]
Got it, thanks Michael!

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
