### ISSUE TITLE
conection sql server external Ip

### ISSUE THREAD

**Issue by Aligtrrz** [MicrosoftDocs/data-integration#10]
I was trying to conect power bi with a external sql server (non local) but doesn´t work, and all the tutorial and docs, just show how to conect to sql server in an local isntance

**Comment by mgblythe** [comment]
Thanks for your comment, @Aligtrrz. I've assigned this issue for review. In the meantime, you might find an answer in the [Power BI Community]( https://community.powerbi.com).

**Comment by DougKlopfenstein** [comment]
@Aligtrrz Thanks for your feedback.

This does not appear to be a documentation related issue. If you need more assistance, you can create a support ticket at support.microsoft.com.
