### ISSUE TITLE
Correction to the file size parameter value meaning and limit

### ISSUE THREAD

**Issue by haidongh** [MicrosoftDocs/data-integration#100]
[Enter feedback here]

This sentence
To configure the size of each log file, change the second number.
Should be changed to 
To configure the size of total log file, change the second number. There is a limit of this number. I found above  2000 is no longer a valid value

This sentence

The following example specifies that 20 log files, each 50 MB in size, will be retained:
GatewayInfo.log,GatewayErrors.log,GatewayNetwork.log,20,50

Should be changed to 

The following example specifies that 20 log files, total 50 MB in size, will be retained:
GatewayInfo.log,GatewayErrors.log,GatewayNetwork.log,20,50
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 918ba65b-b5fd-27be-7fcf-9a44007cb03c
* Version Independent ID: ba9dc70e-151f-0114-7789-df3bf4b4b971
* Content: [Configure log files for the on-premises data gateway](https://docs.microsoft.com/en-us/data-integration/gateway/service-gateway-log-files)
* Content Source: [data-integration/gateway/service-gateway-log-files.md](https://github.com/MicrosoftDocs/data-integration/blob/main/data-integration/gateway/service-gateway-log-files.md)
* Product: **on-premises-data-gateway**
* Technology: ****
* GitHub Login: @arthiriyer
* Microsoft Alias: **arthii**

**Comment by JasonWHowell** [comment]
@DougKlopfenstein this seems like a straight forward doc update. Haidong is pretty savvy on troubleshooting these things. @haidongh if you have a moment, please edit here: https://github.com/MicrosoftDocs/data-integration/blob/main/data-integration/gateway/service-gateway-log-files.md
