### ISSUE TITLE
Request to fix the statement for the datacenter region for the on-premises data gateway doc

### ISSUE THREAD

**Issue by jeeunyoo** [MicrosoftDocs/data-integration#108]
[Enter feedback here]
For this specific statement, it only states that "**For sovereign clouds**, we currently only support installing gateways in the default PowerBI region of your tenant." but there is no information that this also applies for the Power BI default region. (that the datacenter region can't be changed from the PBI default region when installing on-premise data gateway)

It should also include that "For sovereign clouds and Power BI's default region, we currently only support installing gateways in the default PowerBI region of your tenant." 

![image](https://user-images.githubusercontent.com/88862540/129283933-035d7570-2f4a-4ec9-8f6c-230ed4db22d9.png)

---
#### Document Details

https://docs.microsoft.com/en-us/data-integration/gateway/service-gateway-data-region
![image](https://user-images.githubusercontent.com/88862540/129284384-b3b87b48-5626-44ba-b658-13aec5aa070e.png)

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2a07eaa-023b-fbc8-9508-39411425d096
* Version Independent ID: efb6bb0e-5551-e2b3-4e98-3a34188600f3
* Content: [Set the datacenter region for the on-premises data gateway](https://docs.microsoft.com/en-us/data-integration/gateway/service-gateway-data-region)
* Content Source: [data-integration/gateway/service-gateway-data-region.md](https://github.com/MicrosoftDocs/data-integration/blob/main/data-integration/gateway/service-gateway-data-region.md)
* Product: **on-premises-data-gateway**
* Technology: ****
* GitHub Login: @arthiriyer
* Microsoft Alias: **arthii**

**Comment by JasonWHowell** [comment]
Agreed, the installer says this:
![image](https://user-images.githubusercontent.com/5067358/182538100-96b21d43-721e-4bc6-a502-0222ece0acfe.png)
@dougklop there are a few issues for this same point. Seems like a small docs fix to help resolve those.
