### ISSUE TITLE
Please confirm the requirement 

### ISSUE THREAD

**Issue by timp3261** [MicrosoftDocs/data-integration#11]
Hi,
In this page the version of .Net Framework is 4.6. However, in this article(https://powerbi.microsoft.com/zh-tw/blog/on-premises-data-gateway-september-2019-update-is-now-available/) is 4.7.
There are misalignment, please confirm which one is correct.
Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c51a10c-d90c-7690-0979-cd8ce37234c8
* Version Independent ID: 2da65f4c-f128-40b8-1a2b-5ae72c4252d6
* Content: [Install an on-premises data gateway](https://docs.microsoft.com/en-us/data-integration/gateway/service-gateway-install)
* Content Source: [data-integration/gateway/service-gateway-install.md](https://github.com/MicrosoftDocs/data-integration/blob/master/data-integration/gateway/service-gateway-install.md)
* Service: **powerbi**
* Sub-service: **powerbi-gateway**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by mgblythe** [comment]
Thanks for the feedback @timp3261. We updated the doc to clarify:

.NET Framework 4.6 (Gateway release August 2019 and earlier)
.NET Framework 4.7.2 (Gateway release September 2019 and later)
