### ISSUE TITLE
Document is outdated

### ISSUE THREAD

**Issue by Assail** [MicrosoftDocs/data-integration#110]
Document is outdated, screenshots dont match current version as last update was 2019. It doesnt detail how to disable a gateway safely prior to updating without causing power bi update failures

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 860519a0-9f73-14e7-66c1-faaba7f943b5
* Version Independent ID: c9c5d0a1-36e8-72bf-4d8d-5aafe0e01272
* Content: [Update an on-premises data gateway](https://docs.microsoft.com/en-us/data-integration/gateway/service-gateway-update)
* Content Source: [data-integration/gateway/service-gateway-update.md](https://github.com/MicrosoftDocs/data-integration/blob/main/data-integration/gateway/service-gateway-update.md)
* Product: **on-premises-data-gateway**
* Technology: ****
* GitHub Login: @arthiriyer
* Microsoft Alias: **arthii**

**Comment by DougKlopfenstein** [comment]
Hi @Assail 
Thanks for your feedback. The article has been updated with information on how to update gateways safely.
