### ISSUE TITLE
Gateways are not currently supported over Private Links

### ISSUE THREAD

**Issue by masumibaba0830** [MicrosoftDocs/data-integration#112]
[Enter feedback here]
Please add the below sentence on Related considerations.
**Gateways are not currently supported over Private Links.**
![image](https://user-images.githubusercontent.com/89758763/131324944-838711c7-d80f-4eff-8a47-d68188897482.png)

Im support engineer who support Power BI in CSS Japan case.
I confirmed the above parts from the below IcM.
https://portal.microsofticm.com/imp/v3/incidents/details/255834324/home
IcM No:255834324
![image](https://user-images.githubusercontent.com/89758763/131325154-b512e701-e417-4564-ad1a-f3c133427933.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c51a10c-d90c-7690-0979-cd8ce37234c8
* Version Independent ID: 2da65f4c-f128-40b8-1a2b-5ae72c4252d6
* Content: [Install an on-premises data gateway](https://docs.microsoft.com/en-us/data-integration/gateway/service-gateway-install#related-considerations)
* Content Source: [data-integration/gateway/service-gateway-install.md](https://github.com/MicrosoftDocs/data-integration/blob/main/data-integration/gateway/service-gateway-install.md)
* Product: **on-premises-data-gateway**
* Technology: ****
* GitHub Login: @arthiriyer
* Microsoft Alias: **arthii**

**Comment by DougKlopfenstein** [comment]
Hi @masumibaba0830 -
Actually, gateways are supported over private links. The limits of using private links has been added to the gateway installation [related considerations](https://docs.microsoft.com/en-us/data-integration/gateway/service-gateway-install#related-considerations).
