### ISSUE TITLE
Outbound Network Requirements for the VNET Data Gateway

### ISSUE THREAD

**Issue by pnarsi** [MicrosoftDocs/data-integration#117]
Does the VNET Data Gateway need any outbound connectivity to endpoints on the internet in order to function? For example does it need access to any of these Power BI related FQDN documented on this site: https://docs.microsoft.com/en-us/power-bi/admin/power-bi-allow-list-urls or is the communication between the VNET Data Gateway back to the Power Platform managed behind the scenes?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 034ffc7c-77e4-956a-c525-cd420928dca4
* Version Independent ID: 39453075-e824-8ed6-2e9a-63b2714adde7
* Content: [Virtual network (VNet) data gateway architecture](https://docs.microsoft.com/en-us/data-integration/vnet/data-gateway-architecture)
* Content Source: [data-integration/vnet/data-gateway-architecture.md](https://github.com/MicrosoftDocs/data-integration/blob/main/data-integration/vnet/data-gateway-architecture.md)
* Product: **on-premises-data-gateway**
* Technology: ****
* GitHub Login: @arthiriyer
* Microsoft Alias: **arthii**

**Comment by pnarsi** [comment]
In the [FAQ page](https://docs.microsoft.com/en-us/data-integration/vnet/data-gateway-faqs) There is a vague mention of needing outbound rules to AAD and CA depending on the scenario. Is there some documentation somewhere that discusses these scenario? I assume that this would depend on the specific data source being access. Seeing that the list of supported data sources is quite limited it would be great if there was a table that listed all of the supported sources and what outbound connections is required and the specific scenarios where these outbound connections apply. 

![image](https://user-images.githubusercontent.com/7891408/136503568-9a4dcc0f-6ecd-4b2e-b4a7-5260c267d49a.png)

**Comment by jonburchel** [comment]
Hi @pnarsi, and thanks for your question. I confirmed, there are no required ports for the gateway to communicate back to Power BI, and yes, communication to the Power Platform back end is handled behind the scenes.

#please-close
