### ISSUE TITLE
Data gateway cluster maintenance, non-disruptive?

### ISSUE THREAD

**Issue by CB-EP** [MicrosoftDocs/data-integration#119]
I would really appreciate more guidance, even a tutorial for updating cluster nodes in a non-disruptive fashion (disable node with drain, update, resume processing).

I also posted query to this effect in community - https://community.powerbi.com/t5/Service/Updating-on-premises-data-gateway-cluster-with-drain/m-p/2168092/highlight/true#M143712

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53b3be02-f56f-20e3-b1c8-3fd7acca0d00
* Version Independent ID: aefe56f6-cd56-4dac-4d00-55c1f108dd01
* Content: [PowerShell support for on-premises data gateway clusters](https://docs.microsoft.com/en-us/data-integration/gateway/service-gateway-powershell-support)
* Content Source: [data-integration/gateway/service-gateway-powershell-support.md](https://github.com/MicrosoftDocs/data-integration/blob/main/data-integration/gateway/service-gateway-powershell-support.md)
* Product: **on-premises-data-gateway**
* Technology: ****
* GitHub Login: @arthiriyer
* Microsoft Alias: **arthii**

**Comment by abates100** [comment]
Looking for same clarification .  Other content recommends stopping service, is that essentially same as disable or not?  Are running queries just dropped or failed over?

**Comment by DougKlopfenstein** [comment]
Hi @CB-EP and @abates100 
The on-premises data gateway documentation now covers how to migrate your on-premises data gateway with 100% uptime. Go to [Minimize migration downtime](https://docs.microsoft.com/data-integration/gateway/service-gateway-migrate#minimize-migration-downtime) for more information. Note that this requires that you have at least two gateways running in a cluster.
