### ISSUE TITLE
typo on the page

### ISSUE THREAD

**Issue by paullevchuk** [MicrosoftDocs/data-integration#120]
According to my understanding to apply customer values from config to data gateway 
parametr `MashupDisableContainerAutoConfig` should be set to `True` (in doc staed `False`).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 623d0fac-8139-778a-1447-ce62192d2977
* Version Independent ID: eb986506-5f58-c575-a971-f422e398afe7
* Content: [Adjust gateway performance based on server CPU](https://docs.microsoft.com/en-us/data-integration/gateway/service-gateway-performance-cpu)
* Content Source: [data-integration/gateway/service-gateway-performance-cpu.md](https://github.com/MicrosoftDocs/data-integration/blob/main/data-integration/gateway/service-gateway-performance-cpu.md)
* Product: **on-premises-data-gateway**
* Technology: ****
* GitHub Login: @arthiriyer
* Microsoft Alias: **arthii**

**Comment by DougKlopfenstein** [comment]
Hi @paullevchuk 
The wording of the sentence has been changed to be more clear. To enable automatic scaling, MashupDisableContainerAutoConfig must be set to False.
