### ISSUE TITLE
On-premise Gateway trying to open undocumented go.microsoft.com URL

### ISSUE THREAD

**Issue by chrish** [MicrosoftDocs/data-integration#122]
We're operating in an environment with fairly strict requirements when it comes to network openings, and are seeing requests going to https://go.microsoft.com/fwlink/?LinkId=839413 when starting the gateway. This URL does not seem to be documented, but points to a json-file containing all gateway versions and release dates so it is most likely legitimate. Without allowing this URL we can still register the gateway in a cluster, but the cluster sees this as being outdated and cannot communicate with the gateway. Can you please add this and any other required openings to the documentation? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f4daef9a-341c-696a-1d19-de05ffd67588
* Version Independent ID: 7cd18c28-7227-488a-aa28-6b869058e715
* Content: [Adjust communication settings for the on-premises data gateway](https://docs.microsoft.com/en-us/data-integration/gateway/service-gateway-communication)
* Content Source: [data-integration/gateway/service-gateway-communication.md](https://github.com/MicrosoftDocs/data-integration/blob/main/data-integration/gateway/service-gateway-communication.md)
* Product: **on-premises-data-gateway**
* Technology: ****
* GitHub Login: @arthiriyer
* Microsoft Alias: **arthii**

**Comment by jonburchel** [comment]
Thanks for your question @chrish. I confirmed with our product team that this is normal communication that takes place between the gateway and the gateway service. The service might communicate with any addresses within the required listed addresses, as well as any accounted for by the required service tags. This particular URL is covered by a service tag so no specific rule for go.microsoft.com needs to be added.

#please-close
