### ISSUE TITLE
Visualise gateway performance - PBI template out of date?

### ISSUE THREAD

**Issue by baylosb** [MicrosoftDocs/data-integration#125]
The PBIT template provided in the section [Visualize Gateway Performance](https://docs.microsoft.com/en-us/data-integration/gateway/service-gateway-performance#visualize-gateway-performance) seems to be out of date. I think it was created in 2020, we get errors when trying to open with recent versions of PBI desktop.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a144b27-04b6-5d42-9c9f-79bb4cc6730b
* Version Independent ID: 7b00f680-f3a8-3502-94b5-5ca37d36f432
* Content: [Monitor and optimize on-premises data gateway performance](https://docs.microsoft.com/en-us/data-integration/gateway/service-gateway-performance)
* Content Source: [data-integration/gateway/service-gateway-performance.md](https://github.com/MicrosoftDocs/data-integration/blob/main/data-integration/gateway/service-gateway-performance.md)
* Product: **on-premises-data-gateway**
* Technology: ****
* GitHub Login: @arthiriyer
* Microsoft Alias: **arthii**

**Comment by JasonWHowell** [comment]
Close/open to trigger our bot. Please ignore. #please-close

**Comment by jonburchel** [comment]
Thanks for your questino @baylosb. I checked with our product team and they requested for you to open a support incident to investigate this issue further with our support team, who can coordinate with the product developers on the back end if necessary. You can create a new support incident by going to https://support.powerbi.com. Scroll down there and select "Create Support Ticket" to get started.

#please-close
