### ISSUE TITLE
Power BI Gateway Networking with Service Tag

### ISSUE THREAD

**Issue by guangying94** [MicrosoftDocs/data-integration#126]
Service Tag options - AzureAD, ServiceBus, PowerBI don't cover all necessary FQDN in order to get gateway communicate with Power BI. Setting NSG with these 3 service tag, and block internet will prompt error on authentication during setup for this gateway.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f4daef9a-341c-696a-1d19-de05ffd67588
* Version Independent ID: 7cd18c28-7227-488a-aa28-6b869058e715
* Content: [Adjust communication settings for the on-premises data gateway](https://docs.microsoft.com/en-us/data-integration/gateway/service-gateway-communication)
* Content Source: [data-integration/gateway/service-gateway-communication.md](https://github.com/MicrosoftDocs/data-integration/blob/main/data-integration/gateway/service-gateway-communication.md)
* Product: **on-premises-data-gateway**
* Technology: ****
* GitHub Login: @arthiriyer
* Microsoft Alias: **arthii**

**Comment by JasonWHowell** [comment]
Close/open to trigger our bot. Please ignore. #please-close

**Comment by jonburchel** [comment]
Thanks for your question @guangying94. I confirmed with the product team that those tags are required, but additionally, the sites noted in the article must be opened in the firewall, so internet traffic can't be blocked entirely.

#please-close
