### ISSUE TITLE
On Premise Data Gateway Azure Service

### ISSUE THREAD

**Issue by joniangeles** [MicrosoftDocs/data-integration#127]
Hi.  I'm using an On Premise Data Gateway installed in a Windows VM.  I recently found an On Premise Data Gateway Azure Service (portal.azure.com/#create/Microsoft.ConnectionGateway), however I can't find any documentation on this (I think it's quite new).  I want to know the pricing and if it has the same function as the one installed in a Windows machine.
Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a055322-906d-2af9-14f9-79e2ac44265d
* Version Independent ID: 7b6c3a05-12ad-9d44-c00c-cb9e9c971eff
* Content: [What is an on-premises data gateway?](https://docs.microsoft.com/en-us/data-integration/gateway/service-gateway-onprem#feedback)
* Content Source: [data-integration/gateway/service-gateway-onprem.md](https://github.com/MicrosoftDocs/data-integration/blob/main/data-integration/gateway/service-gateway-onprem.md)
* Product: **on-premises-data-gateway**
* Technology: ****
* GitHub Login: @arthiriyer
* Microsoft Alias: **arthii**

**Comment by JasonWHowell** [comment]
That's the Data Gateway for Azure Logic Apps. 
https://docs.microsoft.com/azure/logic-apps/logic-apps-gateway-connection

**Comment by JasonWHowell** [comment]
#please-close
