### ISSUE TITLE
Documentation for delete is incorrect

### ISSUE THREAD

**Issue by paulhusted** [MicrosoftDocs/data-integration#128]
Procedure for removing a Power BI gateway is incorrect.
Suggests the following:
Manage gateways (correct)
Then says to select the gateway and click Delete.
In current UI, there is no delete button on a gateway cluster.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 20180bfa-f4ab-224a-d089-58a06dbf4ac3
* Version Independent ID: f4ab3a3c-397d-01d1-f6d2-05e9085770a1
* Content: [Manage an on-premises data gateway](https://docs.microsoft.com/en-us/data-integration/gateway/service-gateway-manage)
* Content Source: [data-integration/gateway/service-gateway-manage.md](https://github.com/MicrosoftDocs/data-integration/blob/main/data-integration/gateway/service-gateway-manage.md)
* Product: **on-premises-data-gateway**
* Technology: ****
* GitHub Login: @arthiriyer
* Microsoft Alias: **arthii**

**Comment by DougKlopfenstein** [comment]
Hi @paulhusted 
Thanks for the feedback. The documentation has been fixed.
