### ISSUE TITLE
Release history is behind

### ISSUE THREAD

**Issue by JamesTStanley** [MicrosoftDocs/data-integration#129]
[Enter feedback here]
Shouldn't this page be reflecting the gateway releases for Nov/Dec 2021? https://powerbi.microsoft.com/en-us/blog/on-premises-data-gateway-december-2021-update-is-now-available/ 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 27fa3259-c8cf-bd35-7e6a-6f8a1f2a36cf
* Version Independent ID: 187906ab-5531-bce0-084c-d90e3c009c82
* Content: [Previous monthly updates to the on-premises data gateways](https://docs.microsoft.com/en-us/data-integration/gateway/service-gateway-monthly-updates)
* Content Source: [data-integration/gateway/service-gateway-monthly-updates.md](https://github.com/MicrosoftDocs/data-integration/blob/main/data-integration/gateway/service-gateway-monthly-updates.md)
* Product: **on-premises-data-gateway**
* Technology: ****
* GitHub Login: @arthiriyer
* Microsoft Alias: **arthii**

**Comment by DougKlopfenstein** [comment]
Hi @JamesTStanley 
Thanks for your feedback. This was an oversight on our part. The release history is being watched more closely, and is currently up to date.
