### ISSUE TITLE
Minimum Powershell version

### ISSUE THREAD

**Issue by aabundez** [MicrosoftDocs/data-integration#13]
The page says that you need at least Powershell version 5. Should be 6. I couldn't run the Get-DataGatewayClusterStatus cmdlet without installing version 6.

Thanks. -Angel

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53b3be02-f56f-20e3-b1c8-3fd7acca0d00
* Version Independent ID: aefe56f6-cd56-4dac-4d00-55c1f108dd01
* Content: [PowerShell support for on-premises data gateway clusters](https://docs.microsoft.com/en-us/data-integration/gateway/service-gateway-powershell-support#feedback)
* Content Source: [data-integration/gateway/service-gateway-powershell-support.md](https://github.com/MicrosoftDocs/data-integration/blob/master/data-integration/gateway/service-gateway-powershell-support.md)
* Service: **powerbi**
* Sub-service: **powerbi-gateways**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by mgblythe** [comment]
Thanks for your comment, @aabundez. I've assigned this issue to the doc owner for review.

**Comment by inthemedium** [comment]
`Get-DataGatewayClusterStatus` is part of the `DataGateway` module and at present requires PS Core 6 or higher.

All of the commands in `OnPremisesDataGatewayHAMgmt` module require Windows PS 5. Commands from this module will be of the form `*OnPremisesDataGateway*`.

**Comment by arthiriyer** [comment]
Here is the link to the new datagateway module  
https://docs.microsoft.com/en-us/powershell/gateway/overview?view=datagateway-ps

**Comment by DougKlopfenstein** [comment]
The [PowerShell support for on-premises data gateway clusters](https://docs.microsoft.com/data-integration/gateway/service-gateway-powershell-support) article has been updated with this information for some time, so I'm closing as obsolete.
