### ISSUE TITLE
Databricks, not Data Bricks

### ISSUE THREAD

**Issue by kthejoker** [MicrosoftDocs/data-integration#130]
In the supported data sources, Databricks is misspelled as Data Bricks, thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5091585c-6eae-176b-f97b-6e7bf5f18d3f
* Version Independent ID: ece61ded-aee6-c780-25ef-d5c57161df7b
* Content: [Use virtual network (VNet) data gateway and data sources in Power BI](https://docs.microsoft.com/en-us/data-integration/vnet/use-data-gateways-sources-power-bi#supported-azure-data-services)
* Content Source: [data-integration/vnet/use-data-gateways-sources-power-bi.md](https://github.com/MicrosoftDocs/data-integration/blob/main/data-integration/vnet/use-data-gateways-sources-power-bi.md)
* Product: **on-premises-data-gateway**
* Technology: ****
* GitHub Login: @arthiriyer
* Microsoft Alias: **arthii**

**Comment by DougKlopfenstein** [comment]
Hi @kthejoker 
Thanks for the feedback. The spelling has been corrected.
