### ISSUE TITLE
Service tag section has been disappeared in Japanese

### ISSUE THREAD

**Issue by Hyamyam** [MicrosoftDocs/data-integration#132]
Hi Authors,

Please check the contents.

//The end of article in Japanese
![image](https://user-images.githubusercontent.com/73410575/156850878-fbd01da3-e1aa-4ccc-9ef0-ca37c1ac4394.png)

//The end of article in English
![image](https://user-images.githubusercontent.com/73410575/156851134-b300ba8b-b6bb-4b50-8cf2-58de7081ea82.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f4daef9a-341c-696a-1d19-de05ffd67588
* Version Independent ID: 7cd18c28-7227-488a-aa28-6b869058e715
* Content: [Adjust communication settings for the on-premises data gateway](https://docs.microsoft.com/en-us/data-integration/gateway/service-gateway-communication#tls-12-for-gateway-traffic)
* Content Source: [data-integration/gateway/service-gateway-communication.md](https://github.com/MicrosoftDocs/data-integration/blob/main/data-integration/gateway/service-gateway-communication.md)
* Product: **on-premises-data-gateway**
* Technology: ****
* GitHub Login: @arthiriyer
* Microsoft Alias: **arthii**

**Comment by Dealgan12** [comment]
This is a timing issue as this page was in localization and was published on the 18th March. It now contains these sections.
