### ISSUE TITLE
What is meant by "privatized data lake"?

### ISSUE THREAD

**Issue by BennyHarding** [MicrosoftDocs/data-integration#134]
What is meant by "privatized data lake" in this [article](https://docs.microsoft.com/en-us/data-integration/vnet/data-gateway-power-platform-dataflows)?
Does this mean an Azure Data Lake Storage v2 (ADLSv2) with private endpoints configured and public the public endpoint disabled?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dcb6a54a-571c-49c8-3ee6-ba3bed0b6e4f
* Version Independent ID: 9f3a0a29-0a08-6081-a69a-e2a933f0829f
* Content: [Use virtual network (VNet) data gateway in Power Platform dataflows](https://docs.microsoft.com/en-us/data-integration/vnet/data-gateway-power-platform-dataflows?msclkid=c7076abcae9b11eca325fbbdf7a60630)
* Content Source: [data-integration/vnet/data-gateway-power-platform-dataflows.md](https://github.com/MicrosoftDocs/data-integration/blob/main/data-integration/vnet/data-gateway-power-platform-dataflows.md)
* Product: **on-premises-data-gateway**
* Technology: ****
* GitHub Login: @arthiriyer
* Microsoft Alias: **arthii**

**Comment by JasonWHowell** [comment]
Close/open to trigger our bot. Please ignore. #please-close

**Comment by DougKlopfenstein** [comment]
@BennyHarding 
A privatized data lake is just a data lake within a customer’s private network.

If you feel you need more information, please feel free to reopen this issue.
