### ISSUE TITLE
Monitoring template - getting error

### ISSUE THREAD

**Issue by MartinaPoddana** [MicrosoftDocs/data-integration#140]
Hello team,

I have just tried the "We now offer additional query logging and a [Gateway Performance PBI template file](https://download.microsoft.com/download/D/A/1/DA1FDDB8-6DA8-4F50-B4D0-18019591E182/GatewayPerformanceMonitoring.pbit) to visualize the results."

Unfortunately, the template gives me an error on the metadata: "This report has not been upgraded to use the enhanced metadata format, which is required to make modelling changes".

I do not know whom to contact to fix the template, would you?
Alternatively it would be good to list the steps users need to perform to make the template running.

Thank you.
Martina

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a144b27-04b6-5d42-9c9f-79bb4cc6730b
* Version Independent ID: 7b00f680-f3a8-3502-94b5-5ca37d36f432
* Content: [Monitor and optimize on-premises data gateway performance](https://docs.microsoft.com/en-us/data-integration/gateway/service-gateway-performance)
* Content Source: [data-integration/gateway/service-gateway-performance.md](https://github.com/MicrosoftDocs/data-integration/blob/main/data-integration/gateway/service-gateway-performance.md)
* Product: **on-premises-data-gateway**
* Technology: ****
* GitHub Login: @arthiriyer
* Microsoft Alias: **arthii**

**Comment by juanpahub** [comment]
> I did some research on this. the error message appears if log contains commas in the text then the function Table.ExpandTableColumn fails. the issue is that the function can't work with more than 15 columns delimited by comma.
> 
> there for I propose to use combine files function instead. or update logging of the gateway to use quotas for ErrorMessages with commas. I have example GW logs for demonstration.

Hi hokeson,

I have the same issue of Martina, could you please share with your fixed template? I have not been able to fix it yet. 

Many Thanks

**Comment by JasonWHowell** [comment]
Close/open to trigger our bot. Please ignore. #please-close

**Comment by jonburchel** [comment]
Thanks for your question @MartinaPoddana. I checked with the product team who asked me to have you create a new support incident to investigate this further. You can create a new support incident by going to https://support.powerbi.com. Scroll down there and select "Create Support Ticket" to get started. 

#please-close
