### ISSUE TITLE
there ARE licensing prerequsites

### ISSUE THREAD

**Issue by Mike-Crowley** [MicrosoftDocs/data-integration#142]
This FAQ item is incorrect:

_Are there any licensing prerequisites required to install gateways?

There are no licensing restrictions for installing and registering a gateway._

If you do not have a power bi license in the tenant, you cannot register a gateway. An error is reported in the "gatewayconfigurator" log:

_EnterpriseGatewayConfigurator.exe Error: 0 : Error authenticating user: AADSTS500014: The service principal for resource 'https://analysis.windows.net/powerbi/api' is disabled. This indicate that a subscription within the tenant has lapsed, or that the administrator for this tenant has disabled the application, preventing tokens from being issued for it._

I have also confirmed this in support case: 2205020040005038

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c093e8d2-49bb-cf51-02a8-d7792913a5ad
* Version Independent ID: 8fe1e76c-37e2-c6a8-4667-6578164d5b1e
* Content: [On-premises data gateway FAQ](https://docs.microsoft.com/en-us/data-integration/gateway/service-gateway-onprem-faq)
* Content Source: [data-integration/gateway/service-gateway-onprem-faq.yml](https://github.com/MicrosoftDocs/data-integration/blob/main/data-integration/gateway/service-gateway-onprem-faq.yml)
* Product: **on-premises-data-gateway**
* GitHub Login: @arthiriyer
* Microsoft Alias: **arthii**

**Comment by JasonWHowell** [comment]
Close/open to trigger our bot. Please ignore. #please-close

**Comment by jonburchel** [comment]
Thanks for submitting your issue, @Mike-Crowley. I have updated the docs accordingly now in the PR referenced above. #please-close
