### ISSUE TITLE
Request for correction of typographical errors

### ISSUE THREAD

**Issue by fukuyori** [MicrosoftDocs/data-integration#143]
「パフォーマンスと信頼性を向上させるために、ワイヤレス ネットワークではなく優先ネットワークにコンピューターを接続することをお勧めします。」の部分で、「優先」ではなく「有線」となると思います。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 5c51a10c-d90c-7690-0979-cd8ce37234c8
* Version Independent ID: 2da65f4c-f128-40b8-1a2b-5ae72c4252d6
* Content: [オンプレミス データ ゲートウェイをインストールする](https://docs.microsoft.com/ja-jp/data-integration/gateway/service-gateway-install)
* Content Source: [data-integration/gateway/service-gateway-install.md](https://github.com/MicrosoftDocs/data-integration-pr.ja-JP/blob/live/data-integration/gateway/service-gateway-install.md)
* Product: **on-premises-data-gateway**
* Technology: ****
* GitHub Login: @arthiriyer
* Microsoft Alias: **arthii**

**Comment by Dealgan12** [comment]
This has been updated and published.
