### ISSUE TITLE
On trying to update the gateway the screen shows install instead of update.

### ISSUE THREAD

**Issue by rubeesh** [MicrosoftDocs/data-integration#146]
[Enter feedback here]

On trying to update the gateway the screen shows install instead of update.
![image](https://user-images.githubusercontent.com/26519001/170235368-dbe643e1-b0c0-4a14-8a6d-dc53838de18e.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 860519a0-9f73-14e7-66c1-faaba7f943b5
* Version Independent ID: c9c5d0a1-36e8-72bf-4d8d-5aafe0e01272
* Content: [Update an on-premises data gateway](https://docs.microsoft.com/en-us/data-integration/gateway/service-gateway-update)
* Content Source: [data-integration/gateway/service-gateway-update.md](https://github.com/MicrosoftDocs/data-integration/blob/main/data-integration/gateway/service-gateway-update.md)
* Product: **on-premises-data-gateway**
* Technology: ****
* GitHub Login: @arthiriyer
* Microsoft Alias: **arthii**

**Comment by JasonWHowell** [comment]
Close/open to trigger our bot. Please ignore. #please-close

**Comment by DougKlopfenstein** [comment]
Hi @rubeesh 
Did you uninstall the old gateway before running the gateway install program? If so, you can still update your on-premises data gateway by selecting **Install** in the screen you show above, and after entering your credentials, you can select **Migrate, restore, or take over an existing gateway.** Select **Next**, and then in the following screen, enter the name of your old gateway and the recovery key for that gateway.
