### ISSUE TITLE
Option to change region not present in latest gateway version

### ISSUE THREAD

**Issue by jmcarthurcorr** [MicrosoftDocs/data-integration#147]
All of the documents relating to installing an on-premises data gateway refer to checking/changing the region, but this option is not available anywhere in the latest version of the software, 3000.122.8 (April 2022).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2a07eaa-023b-fbc8-9508-39411425d096
* Version Independent ID: efb6bb0e-5551-e2b3-4e98-3a34188600f3
* Content: [Set the datacenter region for the on-premises data gateway](https://docs.microsoft.com/en-us/data-integration/gateway/service-gateway-data-region)
* Content Source: [data-integration/gateway/service-gateway-data-region.md](https://github.com/MicrosoftDocs/data-integration/blob/main/data-integration/gateway/service-gateway-data-region.md)
* Product: **on-premises-data-gateway**
* Technology: ****
* GitHub Login: @arthiriyer
* Microsoft Alias: **arthii**

**Comment by JasonWHowell** [comment]
Same concern as #149

**Comment by JasonWHowell** [comment]
I think the region picker issue is corrected in a later download since I see the option in the later installation. Sorry for the trouble. Closing as resolved. 

![image](https://user-images.githubusercontent.com/5067358/182543210-006cf925-a637-4ae0-a7e5-681d50356cae.png)

**Comment by jmcarthurcorr** [comment]
Following up - I've downloaded the latest and greatest Gateway installer, and this is what I see when taking over a gateway after reinstalling. I don't get the option to change the region on any screen or by using any combination of register/takeover. Only thing I can think of (that the documentation could help clear up) is that we are a GCC customer in a commercial tenant. We were early adopters of O365 before the gov tenants were established.
![image](https://user-images.githubusercontent.com/41071896/183211338-01057ec4-03e0-487c-9958-7dd637f542fa.png)

**Comment by JasonWHowell** [comment]
@jmcarthurcorr 
Oh, maybe you are using Logic Apps gateway? 
Logic Apps gateways are created via the Azure portal, and the region is picked at creation time. 
Details: https://docs.microsoft.com/en-us/azure/logic-apps/logic-apps-gateway-connection#create-azure-gateway-resource

This is the URL to set up the gateway:
https://portal.azure.com/#create/Microsoft.ConnectionGateway

I'm not an expert yet, but trying to help figure this out. Thanks! Jason

**Comment by jmcarthurcorr** [comment]
@JasonWHowell - thanks for the reply. Yes, it's a Logic Apps Gateway, and the part where I'm stumbling is creating the gateway in Azure. No matter what region I select, it can't see the installed on-prem gateway. I did find this in the first link you provided, which confirms my suspicions about GCC. I've gone in circles trying to sort this out and your link is the first indication I've come across defining a difference between setting up an on-prem gateway, and setting one up for Logic Apps. I'll see if I can work through things using that prod@microsoft.com login workaround.
![image](https://user-images.githubusercontent.com/41071896/183473118-04a3e65f-208e-47da-afd5-d6891d83bc49.png)

**Comment by jmcarthurcorr** [comment]
The prod@microsoft.com workaround did the trick.
