### ISSUE TITLE
Link & Details for PBI Gateway Apr & May Edition is not updated

### ISSUE THREAD

**Issue by Sh5678** [MicrosoftDocs/data-integration#149]
[Enter feedback here]

After releasing Power-BI Gateway May Edition, this page has not been updated with the correct link for Apr-2022 edition as well as info on the May-2022 edition. 

Due to this, there is no link available for the Apr-2022 edition download.

Would greatly appreciate having these updated in this page appropriately.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 27fa3259-c8cf-bd35-7e6a-6f8a1f2a36cf
* Version Independent ID: 187906ab-5531-bce0-084c-d90e3c009c82
* Content: [Previous monthly updates to the on-premises data gateways](https://docs.microsoft.com/en-us/data-integration/gateway/service-gateway-monthly-updates)
* Content Source: [data-integration/gateway/service-gateway-monthly-updates.md](https://github.com/MicrosoftDocs/data-integration/blob/main/data-integration/gateway/service-gateway-monthly-updates.md)
* Product: **on-premises-data-gateway**
* Technology: ****
* GitHub Login: @arthiriyer
* Microsoft Alias: **arthii**

**Comment by JasonWHowell** [comment]
@miquelladeboer can you check the latest link - seems like its pointing to April. What's the latest link?

**Comment by JasonWHowell** [comment]
@DougKlopfenstein is updating the page this week. I think this will be resolved by that change.
