### ISSUE TITLE
3 our 4 files created ?

### ISSUE THREAD

**Issue by spiralcb** [MicrosoftDocs/data-integration#15]
Hi, 
I'm trying to use this but only 3 files are generated. 
- The Query Execution Report
- The Query Execution Aggregation Report
- The System Counter Aggregation Report
Cannot find this one : The Query Start Report

And I obtain a error on the report. 
"Column 'QueryTrackingId' in Table 'QueryExecutionReport' contains a duplicate value '46be0ce1-b16d-42aa-ae56-8e6176f570ed' and this is not allowed for columns on the one side of a many-to-one relationship or for columns that are used as the primary key of a table." 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a144b27-04b6-5d42-9c9f-79bb4cc6730b
* Version Independent ID: 7b00f680-f3a8-3502-94b5-5ca37d36f432
* Content: [Monitor and optimize on-premises data gateway performance](https://docs.microsoft.com/en-us/data-integration/gateway/service-gateway-performance#feedback)
* Content Source: [data-integration/gateway/service-gateway-performance.md](https://github.com/MicrosoftDocs/data-integration/blob/master/data-integration/gateway/service-gateway-performance.md)
* Technology: **on-premises-data-gateway**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by mgblythe** [comment]
Thanks for your comment, @spiralcb. I've assigned this issue to the doc owner for review.

**Comment by olyamusok** [comment]
Query Start Report has been made available in October so if your gateway is on earlier release then you will see only 3 log files. In terms of the Query Editor Error - it is not mentioned anywhere in documentation (afaik) but `QueryTrackingID` is not a unique row identifier and there will be records in `Query Execution Report` with the same ID if there was an error and then a retry, report template is built by having a 1 to 1 relationship between `Query Execution Report` and `Query Start Report` which starts breaking if you have those retries with duplicate query ids. This should be on MS Gateway team to document and fix

**Comment by DougKlopfenstein** [comment]
@spiralcb Closed because the questions were answered.
