### ISSUE TITLE
What is a swift tunnel?

### ISSUE THREAD

**Issue by sidprasher** [MicrosoftDocs/data-integration#151]
Can this page link to documentation on the SWIFT tunnel? What does it mean in terms of network traffic?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 034ffc7c-77e4-956a-c525-cd420928dca4
* Version Independent ID: 39453075-e824-8ed6-2e9a-63b2714adde7
* Content: [Virtual network (VNet) data gateway architecture](https://docs.microsoft.com/en-us/data-integration/vnet/data-gateway-architecture)
* Content Source: [data-integration/vnet/data-gateway-architecture.md](https://github.com/MicrosoftDocs/data-integration/blob/main/data-integration/vnet/data-gateway-architecture.md)
* Service: **virtual-network-data-gateway**
* Technology: ****
* GitHub Login: @arthiriyer
* Microsoft Alias: **arthii**

**Comment by JasonWHowell** [comment]
Close/open to trigger our bot. Please ignore. #please-close

**Comment by JasonWHowell** [comment]
#please-open

**Comment by sidprasher** [comment]
Is there any update for this issue?

**Comment by DougKlopfenstein** [comment]
Hi @sidprasher 
The issue has been fixed in the latest documentation. We no longer use the phrase "SWIFT tunnel" because the phrase was confusing. We now use the phrase "internal Microsoft tunnel", which refers to an internal Microsoft tunnel that doesn't reach the public internet.
