### ISSUE TITLE
Manage Data Source Grayed Out for Non Admins

### ISSUE THREAD

**Issue by SamirFarhat** [MicrosoftDocs/data-integration#153]
The document shows how to manage a Data Source, and shows the different roles (Admin, user, user with Sharing).
The problem is that a Non Admin cannot know who is the Admin, as the Manage Users is grayed out.
Is this expected ?
![image](https://user-images.githubusercontent.com/14938496/174566120-9f858c47-ecd0-4d0a-a6d6-eb1263eea8c8.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bbd6bf84-488e-10a4-eaee-0d7a54693d35
* Version Independent ID: bbd6bf84-488e-10a4-eaee-0d7a54693d35
* Content: [Manage security roles](https://docs.microsoft.com/en-us/data-integration/gateway/manage-security-roles)
* Content Source: [data-integration/gateway/manage-security-roles.md](https://github.com/MicrosoftDocs/data-integration/blob/main/data-integration/gateway/manage-security-roles.md)
* Product: **on-premises-data-gateway**
* Technology: ****
* GitHub Login: @miquelladeboer
* Microsoft Alias: **mideboer**

**Comment by JasonWHowell** [comment]
Close/open to trigger our bot. Please ignore. #please-close

**Comment by jonburchel** [comment]
Hi @SamirFarhat, and thanks for your question. I confirmed that yes, this is the expected behavior when the user is not an admin.

**Comment by jonburchel** [comment]
#please-close
