### ISSUE TITLE
Where is the "config file" ?

### ISSUE THREAD

**Issue by nstraw** [MicrosoftDocs/data-integration#155]
Hi doc team,

in the 1st part of the article, in the section "Configure Performance logging", it is not clear as who and where is the "config file" we should modify :
 
![image](https://user-images.githubusercontent.com/35227452/174657999-9f09d99d-95e2-4d17-a7d6-c2d68a799f47.png)

As we can find 4 config files in the Gateway folder, it can be confusing.

![image](https://user-images.githubusercontent.com/35227452/174658358-327dcd39-3e6e-42eb-b9db-4afa4b660d61.png)

It would be very useful to have the exact target config file name and path.

My 2 cents,

Have a good one,

Nicolas

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a144b27-04b6-5d42-9c9f-79bb4cc6730b
* Version Independent ID: 7b00f680-f3a8-3502-94b5-5ca37d36f432
* Content: [Monitor and optimize on-premises data gateway performance](https://docs.microsoft.com/en-us/data-integration/gateway/service-gateway-performance)
* Content Source: [data-integration/gateway/service-gateway-performance.md](https://github.com/MicrosoftDocs/data-integration/blob/main/data-integration/gateway/service-gateway-performance.md)
* Product: **on-premises-data-gateway**
* Technology: ****
* GitHub Login: @arthiriyer
* Microsoft Alias: **arthii**

**Comment by JasonWHowell** [comment]
@arthiriyer please take a look.

**Comment by JasonWHowell** [comment]
@joshger do you know anyone in CSS that could clarify this point? I'd love to make the troubleshooting scenarios super clear in these docs.

**Comment by JasonWHowell** [comment]
@nstraw I see the logging option is available in the Data Gateway User Interface:
![image](https://user-images.githubusercontent.com/5067358/182543800-9fa10656-7670-45ab-8fe1-358959383264.png)

**Comment by JoshGer** [comment]
> @JoshGer do you know anyone in CSS that could clarify this point? I'd love to make the troubleshooting scenarios super clear in these docs.

The properties referenced in the doc are located in C:\Program Files\On-premises data gateway\Microsoft.PowerBI.DataMovement.Pipeline.GatewayCore.dll.config

![image](https://user-images.githubusercontent.com/32432387/182634674-689359c1-a173-4baa-a18d-d4762165750d.png)

**Comment by JasonWHowell** [comment]
I have updated the doc, and the change should go live 3pm PST today. Thanks for the feedback @nstraw, and thanks to @joshger for the help.
