### ISSUE TITLE
VNet data gateway cross-tenant scenarios

### ISSUE THREAD

**Issue by jasonhendrix** [MicrosoftDocs/data-integration#158]
Regarding this FAQ:
_Does VNet data gateway support cross-tenant scenarios?
No. The VNet data gateway must be created in the same tenant as the Power BI tenant._

If the Power BI VNet data gateway and Power BI service are both in the same tenant, but the actual source data is an Azure SQL Database  in a second tenant that has a peered VNet to the same VNet used for the Power BI VNet data gateway, is that a supported scenario?

The environment I'm describing is:
 
    -Two Azure Subscriptions each in different Azure Tenants (Subscription A and Subscription B)
        -In Subscription A:
            -Create an Azure SQL Database
            -Connect the Azure SQL Database to an Azure VNet
            -Configure the Azure SQL Server Firewall to:
                -NOT allow Azure services and resources to access this server
                -Only allow access from “selected networks” that includes only the VNet
            -Peer the Azure VNet in this Azure Subscription to the Azure VNet in the other Azure Subscription
        -In Subscription B:
            -Create a Power BI Dataset that sources from the above SQL Database
            -Create an Azure VNet
            -Peer the Azure VNet in this Azure Subscription to the Azure VNet in the other Azure Subscription
            -In the Power BI Service, configure Power BI VNet Gateways and connect to the VNet
            -In the Power BI Dataset settings, configure the SQL Database connection to be made via the VNet Gateway
            -Refresh the Dataset hourly

I have noticed intermittent failures when testing this scenario.  It does work, but not consistently enough for production use.  Is this a known issue?  Is it expected to work when Power BI VNet Gateways move to General Availability?

**Comment by DougKlopfenstein** [comment]
Hi @jasonhendrix 
Thank you for your feedback.

This seems to be product feedback or a request for product support rather than documentation feedback. For information about product feedback or customer support for gateways in Power BI, go to [Power BI Support](https://powerbi.microsoft.com/support/).
