### ISSUE TITLE
Supported Azure data services - should include PostgreSQL

### ISSUE THREAD

**Issue by denglishbi** [MicrosoftDocs/data-integration#163]
In the list of supported data services PostgreSQL is not included.

This is one of the sources that is available now just don't believe it was ever announced.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5091585c-6eae-176b-f97b-6e7bf5f18d3f
* Version Independent ID: ece61ded-aee6-c780-25ef-d5c57161df7b
* Content: [Use virtual network (VNet) data gateway and data sources in Power BI](https://docs.microsoft.com/en-us/data-integration/vnet/use-data-gateways-sources-power-bi)
* Content Source: [data-integration/vnet/use-data-gateways-sources-power-bi.md](https://github.com/MicrosoftDocs/data-integration/blob/main/data-integration/vnet/use-data-gateways-sources-power-bi.md)
* Service: **virtual-network-data-gateway**
* GitHub Login: @nikkiwaghani
* Microsoft Alias: **nikkiwaghani**

**Comment by DougKlopfenstein** [comment]
Hi @denglishbi 

Thanks for the feedback! PostgreSQL has been added to the data services list.
