### ISSUE TITLE
Please review publicly available information about the operation of the Virtual Network Data Gateway.

### ISSUE THREAD

**Issue by userAhappy** [MicrosoftDocs/data-integration#164]
Please tell me if the architecture diagram is correct.
Title: Virtual Network Data Gateway Architecture
URL : https://docs.microsoft.com/en-us/data-integration/vnet/data-gateway-architecture

1. Regarding the architecture diagram on this site, the IP addresses of the two subnets in the two Vnets connected by Swift Tunnel are duplicated, please tell me if this is the correct value. 

2.Please let us know if the Swift Tunnel connecting the Vnet refers to the Vnet Peering in the following public information.
Title : Virtual network peering
URL : https://docs.microsoft.com/en-us/azure/virtual-network/virtual-network-peering-overview

In our customer's environment, there is no configuration item called Swift Tunnel when building a virtual network data gateway.
Please let us know if there are other applicable configuration locations.

3. Please tell us how many virtual network data gateways there are.
In the architecture diagram, there are two Container Host VMs and a Frontend VM in the Platform VNET, but the customer's environment was different.
In the customer's environment, there is a setting for the number of VMs, but there is no setting to determine the role of VMs, i.e., Container Host VM and Frontend VM. 

4.Why are there two NICs connected to the Container Host VM?
Does Swift Tunnel represent a single VM configuring a NIC to straddle two VNETs in the same region, with two NICs connected to route between each Vnet?
If so, routing is not possible if there are duplicate IP addresses between the Vnet as per question 1.

5. Please tell me that the Virtual Network Data Gateway is not visible on the Azure Portal.
The NICs could not be verified on the connected devices of the target Vnet and neither could the VMs.

**Comment by JasonWHowell** [comment]
Close/open to trigger our bot. Please ignore.

**Comment by jonburchel** [comment]
Thanks @userAhappy for your dedication to our documentation. Unfortunately, at this time we have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. The requested updates have not been made since the creation of this issue, and the timeline for resolution may vary based on resourcing, so we've created an internal work item to incorporate your suggestions. We are closing this issue for now, but feel free to comment here as necessary. #please-close
