### ISSUE TITLE
Link to Jul-2022 version of On-premises data gateway download is not updated

### ISSUE THREAD

**Issue by Sh5678** [MicrosoftDocs/data-integration#167]
This page (https://docs.microsoft.com/en-us/data-integration/gateway/service-gateway-monthly-updates) seem to be last updated on 08/05/2022 while the latest data gateway version is released on 08/15/2022.

Due to the convention followed for latest version link, the above page on monthly updates is having a link for the latest version and then from Jun-2022 versions but the intermediate Jul-2022 version is not available. This seem to be a regular pattern -- recommend whenever a new Gateway version is released, include a step to update this monthly update page also as otherwise it seem to be getting missed out repeatedly and getting updated only after being pointed out by us.

**Comment by JasonWHowell** [comment]
Close/open to trigger our bot. Please ignore.

**Comment by nikkiwaghani** [comment]
@JasonWHowell  why was this reopened? What is the action item on this now? The page has been updated.

**Comment by JasonWHowell** [comment]
Did you respond to the customer? I don't see anything above.

**Comment by JasonWHowell** [comment]
@Sh5678 I think the [page](https://docs.microsoft.com/en-us/data-integration/gateway/service-gateway-monthly-updates) is now updated, and this issue is resolved. Thanks for letting us know your feedback about docs. ~Jason
