### ISSUE TITLE
link to Gateway Performance PBI template 

### ISSUE THREAD

**Issue by hokeson** [MicrosoftDocs/data-integration#168]
hi, 
there is mentioned the gateway performance template in the document twice.
[Gateway Performance PBI template file](https://download.microsoft.com/download/b/1/b/b1b229f4-a142-4d8a-8968-19e4ae95bc37/OnPremiseDataGatewayLogs.pbit)
[Gateway Performance PBI template](https://download.microsoft.com/download/D/A/1/DA1FDDB8-6DA8-4F50-B4D0-18019591E182/GatewayPerformanceMonitoring.pbit)
each of them refers to different .pbit. the first one is a newer one in my eyes.

There is one more page Query Concurrent count available in the new template.
an explanation in the document for this page would be helpful as well. there should exist a recommended limit of 40 concurrent queries I didn't find anywhere else mentioned in documentation.

would be a great argument for overloaded gateways if available.
thank you in advance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a144b27-04b6-5d42-9c9f-79bb4cc6730b
* Version Independent ID: 7b00f680-f3a8-3502-94b5-5ca37d36f432
* Content: [Monitor and optimize on-premises data gateway performance](https://docs.microsoft.com/en-us/data-integration/gateway/service-gateway-performance)
* Content Source: [data-integration/gateway/service-gateway-performance.md](https://github.com/MicrosoftDocs/data-integration/blob/main/data-integration/gateway/service-gateway-performance.md)
* Product: **on-premises-data-gateway**
* GitHub Login: @miquelladeboer
* Microsoft Alias: **mideboer**

**Comment by JasonWHowell** [comment]
Close/open to trigger our bot. Please ignore.

**Comment by DougKlopfenstein** [comment]
Hi @hokeson 
Thanks for the feedback! The second link was obsolete, so it was changed to match the link in the first part of the article.
