### ISSUE TITLE
Incorrect Payload limit of Datagateway in docs?

### ISSUE THREAD

**Issue by renebik** [MicrosoftDocs/data-integration#17]
[The Considerations section ](https://docs.microsoft.com/en-us/data-integration/gateway/service-gateway-onprem#considerations) mentioned 2-MB payload as a limit, but I am able to write larger files to on-prem server.
Is the mentioned payload limit correct, as I only get an error when trying to write a file larger than 20 MB.

    {
      "status": 413,
      "message": "The file contains 45365726 bytes which exceeds the maximum 20971520 
    bytes.\r\nclientRequestId: xxx",
      "source": "filesystem-xxx.p.azurewebsites.net"
    }

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a055322-906d-2af9-14f9-79e2ac44265d
* Version Independent ID: 7b6c3a05-12ad-9d44-c00c-cb9e9c971eff
* Content: [What is an on-premises data gateway?](https://docs.microsoft.com/en-us/data-integration/gateway/service-gateway-onprem)
* Content Source: [data-integration/gateway/service-gateway-onprem.md](https://github.com/MicrosoftDocs/data-integration/blob/master/data-integration/gateway/service-gateway-onprem.md)
* Technology: **on-premises-data-gateway**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by mgblythe** [comment]
Thanks for your comment, @renebik. I've assigned this issue to the doc owner for review.

**Comment by JasonWHowell** [comment]
Same issue in #68 #67 and #17

**Comment by DougKlopfenstein** [comment]
Hi @renebik 
Thanks for the feedback. This issue has finally been resolved - [Considerations](https://docs.microsoft.com/data-integration/gateway/service-gateway-onprem#considerations)
