### ISSUE TITLE
Cross-region VNET gateway

### ISSUE THREAD

**Issue by UnoSD** [MicrosoftDocs/data-integration#173]
The documentation seems to be a bit confusing on this paragraph:

`VNet data gateways are created in your tenant's home region by default and there's currently no option to change the VNet data gateway region. Based on this limitation, VNet data gateways can only be used in Power platform environments in the home region of your tenant.`

in particular: `VNet data gateways can only be used in Power platform environments in the home region of your tenant`

A chat with the product group confirmed that a PBI in one region can communicate with a VNET in a different region; the statement above is unclear, but sounds like it is saying the opposite.

Can you please clarify this section specifying what it means and clarifying if cross-region communication is possible?

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d47e61c8-a5b8-0a8b-06dd-c242a0acd06c
* Version Independent ID: e80385c1-b254-525d-b5ec-2b653e7763d8
* Content: [What is a virtual network (VNet) data gateway (Preview)](https://learn.microsoft.com/en-us/data-integration/vnet/overview)
* Content Source: [data-integration/vnet/overview.md](https://github.com/MicrosoftDocs/data-integration/blob/main/data-integration/vnet/overview.md)
* Service: **virtual-network-data-gateway**
* GitHub Login: @nikkiwaghani
* Microsoft Alias: **nikkiwaghani**

**Comment by miquelladeboer** [comment]
the vnet can be in a different region, but the vnet registration (metadata) will be in the same region as the home region.

**Comment by jonburchel** [comment]
Thanks @UnoSD for your question. I see @miquelladeboer was able to answer, so I will go ahead and close this issue out now. #please-close
