### ISSUE TITLE
Virtual Network Data Gateways & PPU Licensing

### ISSUE THREAD

**Issue by jamesdbxt** [MicrosoftDocs/data-integration#176]
Hi,

This [documentation](https://learn.microsoft.com/en-us/data-integration/vnet/use-data-gateways-sources-power-bi) mentions that Virtual Network data gateways are only available in Power BI Premium and Premium Per User (PPU) workspaces.

![image](https://user-images.githubusercontent.com/59151501/196824613-ec0a5ba0-ec35-4b5f-9780-fbc4e061624e.png)

Is this correct based on the below screenshot? In this scenario the user has a 'Premium Per User' license but they are unable to use the VNET Gateway I have configured for them.

![power bivnet](https://user-images.githubusercontent.com/59151501/196824672-a266f221-357b-42f7-b515-2f9c6c55a839.png)

Lastly, this may not be correct forum but is there any timeline on when this feature will be GA'd and therefore available to more licensing arrangements? This limitation is preventing us from removing public IPs of our data infrastructure.

Regards,
James

**Comment by jonburchel** [comment]
Thanks for your question @jamesdbxt. This was updated in PR https://github.com/MicrosoftDocs/data-integration-pr/pull/515 to reflect that PPU licensing no longer supports VNet since the public preview ended. #please-close
