### ISSUE TITLE
Supported Data Sources - SQL Server in Azure VM?

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftDocs/data-integration#185]
The page mentions

> Azure SQL

as the supported platform. Does this include SQL Server in an Azure VM? If so, what versions/configuratoins are supported?

According to https://learn.microsoft.com/en-us/data-integration/vnet/sql-server-and-custom-connectors SQL Server may be supported. However it's unclear and we do not want to make any assumption..

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5091585c-6eae-176b-f97b-6e7bf5f18d3f
* Version Independent ID: ece61ded-aee6-c780-25ef-d5c57161df7b
* Content: [Use virtual network (VNet) data gateway and data sources in Power BI](https://learn.microsoft.com/en-us/data-integration/vnet/use-data-gateways-sources-power-bi)
* Content Source: [data-integration/vnet/use-data-gateways-sources-power-bi.md](https://github.com/MicrosoftDocs/data-integration/blob/main/data-integration/vnet/use-data-gateways-sources-power-bi.md)
* Service: **virtual-network-data-gateway**
* GitHub Login: @nikkiwaghani
* Microsoft Alias: **nikkiwaghani**

**Comment by jashwood** [comment]
Any chance of getting an answer on this? We would like to know too

**Comment by DougKlopfenstein** [comment]
@VitalyMCT @jashwood 
SQL server on a VM is not supported. The [VNet data gateway support for Power Automate SQL Server and custom connectors (Preview)](https://learn.microsoft.com/en-us/data-integration/vnet/sql-server-and-custom-connectors) article refers to the direct VNet used in Power Apps/Automate, which is created in the Power Platform admin center in the Gateway drop-down box, not the VNet data gateway.

**Comment by jashwood** [comment]
Thanks Doug

**Comment by VitalyMCT** [comment]
@DougKlopfenstein Understood. Could you please amend the article accordingly?

Microsoft's definition of Azure SQL includes SQL Server on Azure VM (https://azure.microsoft.com/en-us/products/azure-sql/#sql-database). So the wording in the article as it stands now is incorrect.

**Comment by jonburchel** [comment]
Thanks @VitalyMCT for your dedication to our documentation. Unfortunately, at this time we have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. The requested updates have not been made since the creation of this issue, and the timeline for resolution may vary based on resourcing, so we've created an internal work item to incorporate your suggestions. We are closing this issue for now, but feel free to comment here as necessary. #please-close

**Comment by VitalyMCT** [comment]
Can you please fix this? It's a one-word change: "SQL Server" => "Azure SQL". Customers keep getting confused.

**Comment by jonburchel** [comment]
Hi @VitalyMCT. I just checked and the document does refer to Azure SQL. Sorry for the confusion in the closure comment. :) Thanks for helping us improve the docs!

**Comment by jonburchel** [comment]
@VitalyMCT Ah indeed! I was somehow looking at the wrong doc before! I fixed it now. Thanks again for catching this and helping us keep the docs up to date!
