### ISSUE TITLE
The note about setting the TMP environment variables is incorrect

### ISSUE THREAD

**Issue by dbrownems** [MicrosoftDocs/data-integration#186]
The note: "To change the environment variables in Windows, from the Start menu, select Search, enter Environment Variables, select Edit the system environment variables, and from System Pro..."  is incorrect.

System environment variables are overwritten by user environment variables, and TMP is set for both the system and the users.  EG

![image](https://user-images.githubusercontent.com/28908684/199796833-8fed05e3-3131-4fe8-9696-c96b835f760e.png)

But when I launch a process it has the user environment variable for TMP not the system environment variabel.

![image](https://user-images.githubusercontent.com/28908684/199797127-c47f0bc7-6320-4c06-91b8-b4d54e7693ed.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 47a774c7-6818-74b7-cedc-727c68e2f390
* Version Independent ID: 47a774c7-6818-74b7-cedc-727c68e2f390
* Content: [Configure gateway disk space](https://learn.microsoft.com/en-us/data-integration/gateway/service-gateway-configure-disk-space#gateway-spooling-data)
* Content Source: [data-integration/gateway/service-gateway-configure-disk-space.md](https://github.com/MicrosoftDocs/data-integration/blob/main/data-integration/gateway/service-gateway-configure-disk-space.md)
* Product: **on-premises-data-gateway**
* GitHub Login: @miquelladeboer
* Microsoft Alias: **mideboer**

**Comment by JasonWHowell** [comment]
@dbrownems The gateway service runs as a background service account even when no user is logged into the computer. 

Do you have your gateway configured to run as your personal account, or as the service account  NT Service\PBIEgwService?

I'm thinking that for the gateway service, the user profile isn't loaded, so it doesn't perceive any user temp environment variable.

When you log in, that's typically a different user than the service, and your user profile is fully loaded, overriding the system environment variables. 

Let me know what you think. Thx, Jason

**Comment by dbrownems** [comment]
Apparently, the user environment is not dependent on loading the profile.  This is after changing the system environment variable and rebooting.

![image](https://user-images.githubusercontent.com/28908684/201430592-092e4e7b-78c8-499a-a9e2-0f0d737e8caf.png)

**Comment by JasonWHowell** [comment]
Sounds like the OS has changed over the years. I remember so many issues with service account environment variables. Which version of Windows are you using?

**Comment by dbrownems** [comment]
I'm on Windows 11.

And there typically aren't many user environment variables.  And the user's PATH is appended to the system's PATH;  only for TEMP and TMP are the system environment variables replaced by the user environment variable.

David

David Browne | Principal Program Manager | Power BI CAT | Microsoft Corporation | (o) 469-775-2041 | (c) 214-394-9198 | ***@***.******@***.***><https://mail.microsoft.com/OWA/UrlBlockedError.aspx>
________________________________

**Comment by DougKlopfenstein** [comment]
The wording in the section you identified actually does include the correct information. It just might be a little confusing.

The "select Edit the system environment variables" is actually referring to the phrase found by the windows search; it doesn't actually refer to what you are supposed to change. Here is what the doc says:

<img width="647" alt="image" src="https://user-images.githubusercontent.com/40473364/202814928-4fb63480-0a3e-4c55-b5b1-3895c19f52a5.png">

Here's the results of the search for Environment Variables from the note:

<img width="224" alt="image" src="https://user-images.githubusercontent.com/40473364/202814699-0dd85b2b-7041-47e2-ad1e-1c3e6f919333.png">

So the first sentence from the article says to "change TMP for the gateway user", not the system. However, I agree that this should be clearer.

**Comment by JasonWHowell** [comment]
#please-close Hope this discussion was helpful, but let us know if we need to discuss further David.
