### ISSUE TITLE
Typo in page 

### ISSUE THREAD

**Issue by martaequintao** [MicrosoftDocs/data-integration#189]
There is a typo in the word "following" here:
![image](https://user-images.githubusercontent.com/45423022/201392727-016ee417-573c-4b65-a042-56c2f443d803.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: cc5b41d6-127a-a1ba-a9ad-fe1d0549b5a4
* Version Independent ID: cc5b41d6-127a-a1ba-a9ad-fe1d0549b5a4
* Content: [Step by step guide on configuring your proxy settings](https://learn.microsoft.com/en-us/data-integration/gateway/service-gateway-proxy-setup-guide)
* Content Source: [data-integration/gateway/service-gateway-proxy-setup-guide.md](https://github.com/MicrosoftDocs/data-integration/blob/main/data-integration/gateway/service-gateway-proxy-setup-guide.md)
* Product: **on-premises-data-gateway**
* GitHub Login: @miquelladeboer
* Microsoft Alias: **mideboer**

**Comment by DougKlopfenstein** [comment]
Hi @martaequintao 
Thanks for the feedback! The typo has bee fixed.
