### ISSUE TITLE
Supported server installations

### ISSUE THREAD

**Issue by angoo-atea** [MicrosoftDocs/data-integration#19]
Is it supported to install a data gateway on a server running any kind of high end application - e.g. a server running SharePoint, SQL, Exchange, AD etc ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c51a10c-d90c-7690-0979-cd8ce37234c8
* Version Independent ID: 2da65f4c-f128-40b8-1a2b-5ae72c4252d6
* Content: [Install an on-premises data gateway](https://docs.microsoft.com/en-us/data-integration/gateway/service-gateway-install)
* Content Source: [data-integration/gateway/service-gateway-install.md](https://github.com/MicrosoftDocs/data-integration/blob/master/data-integration/gateway/service-gateway-install.md)
* Technology: **on-premises-data-gateway**
* GitHub Login: @arthiriyer
* Microsoft Alias: **arthii**

**Comment by DougKlopfenstein** [comment]
@angoo-atea Thanks for your feedback. Yes, you can install a gateway on a machine running a high end application, but this may degrade gateway performance. If you do so, you should monitor the gateway closely to check if there is any kind of resource contention.
