### ISSUE TITLE
OnPremiseDataGatewayLogs.pbit gives duplicate value error in QueryStartReport

### ISSUE THREAD

**Issue by Sh5678** [MicrosoftDocs/data-integration#200]
We are using Oct-2022 version of On-premise Gateway installed on 2 different servers setup as Gateway Cluster and trying to use the latest OnPremiseDataGatewayLogs.pbit to review the Gateway Logs.

Irrespective of whether we use Oct-2022, Nov-2022 & Dec-2022 versions of PBI Desktop OR the log files from either of the above 2 Gateway servers, we continue to get below error:
**QueryStartReport
Column 'QueryTrackingId' in Table 'QueryStartReport' contains a duplicate value 'd031b426-cbf9-4a9f-8df6-cfc241c1fe1d' and this is not allowed for columns on the one side of a many-to-one relationship or for columns that are used as the primary key of a table.**

What is causing this error and how can this be resolved?

**Comment by DougKlopfenstein** [comment]
Hi @Sh5678 
Thank you for your feedback.

This seems to be product feedback or a request for product support rather than documentation feedback. For information about product feedback or customer support for gateways in Power BI, go to [Power BI Support](https://powerbi.microsoft.com/support/).
