### ISSUE TITLE
Reference to Service 

### ISSUE THREAD

**Issue by jaganth** [MicrosoftDocs/data-integration#202]
[Enter feedback here]

Reference to "ServiceBus" in the bulleted list in section https://learn.microsoft.com/en-us/data-integration/gateway/service-gateway-communication#service-tags is misleading.

The bulleted list is list of service on which data gateway has a dependency.

The text following the bulleted list goes on to says ServiceBus tags are NOT relevant for data gateway because is not meant for Relay.

ASK
=====
- remove ServiceBus from bulleted list.
- Add below text as a "Note"

_The on-premises data gateway uses Azure Relay for some communication. However, there are no service tags for the Azure Relay service. ServiceBus service tags specifically pertain to the Service queues and topics feature, but not for Azure Relay.

The AzureCloud service tag represents all global Azure Data Center IP addresses. Since Azure Relay service is built on top of Azure Compute, Azure Relay public IPs are a subset of the AzureCloud IPs. More information: [Azure service tags overview](https://learn.microsoft.com/en-us/azure/virtual-network/service-tags-overview)_
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f4daef9a-341c-696a-1d19-de05ffd67588
* Version Independent ID: 7cd18c28-7227-488a-aa28-6b869058e715
* Content: [Adjust communication settings for the on-premises data gateway](https://learn.microsoft.com/en-us/data-integration/gateway/service-gateway-communication)
* Content Source: [data-integration/gateway/service-gateway-communication.md](https://github.com/MicrosoftDocs/data-integration/blob/main/data-integration/gateway/service-gateway-communication.md)
* Product: **on-premises-data-gateway**
* GitHub Login: @miquelladeboer
* Microsoft Alias: **mideboer**

**Comment by JasonWHowell** [comment]
@jaganth 

I think the statement is intending to say users have to keep the ServiceBus tag for it to work, because there isn't a dedicated Relay service tag available to use instead.  I can see how it reads a little confusing, but I still think this is a true statement. 

> The on-premises data gateway uses Azure Relay for some communication. However, there are no service tags for the Azure Relay service. ServiceBus service tags specifically pertain to the Service queues and topics feature, but not for Azure Relay.
