### ISSUE TITLE
December release is missing (along with more detailed release notes)

### ISSUE THREAD

**Issue by Teckfahimkanji** [MicrosoftDocs/data-integration#205]
Hi,

Please add the December release to this page & 

So for the last 3 updates, the release notes haven't described ANYTHING at all in terms of what's been implemented in the release.  Can you guys actually populate something.  It could be as simple as "minor bugs" or "product optimization" or or something like that?

It's hard to know whether or not I should be concerned about deploying the new version or not without some kind of detail.

Cheers,

Fahim.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 27fa3259-c8cf-bd35-7e6a-6f8a1f2a36cf
* Version Independent ID: 187906ab-5531-bce0-084c-d90e3c009c82
* Content: [Previous monthly updates to the on-premises data gateways](https://learn.microsoft.com/en-us/data-integration/gateway/service-gateway-monthly-updates)
* Content Source: [data-integration/gateway/service-gateway-monthly-updates.md](https://github.com/MicrosoftDocs/data-integration/blob/main/data-integration/gateway/service-gateway-monthly-updates.md)
* Product: **on-premises-data-gateway**
* GitHub Login: @miquelladeboer
* Microsoft Alias: **mideboer**

**Comment by JasonWHowell** [comment]
Hi @Teckfahimkanji  

The December release came out mid-January. Odd timing I know.

https://powerbi.microsoft.com/en-us/blog/on-premises-data-gateway-december-release/
https://learn.microsoft.com/en-us/data-integration/gateway/service-gateway-monthly-updates

Good feedback about having some (any) details in the release notes. @nikkiwaghani if you have any context, please assist.

Thanks! Jason

**Comment by DougKlopfenstein** [comment]
Hi @Teckfahimkanji 
Thanks for the feedback! The last several month's release notes have included more information about what's available in the current release.
