### ISSUE TITLE
Logging is intermittent

### ISSUE THREAD

**Issue by SteveWest1** [MicrosoftDocs/data-integration#21]
We've enabled this feature for all of our gateways.  All of the gateways have days or weeks gaps in logging, even though we know refreshes are occurring constantly on these gateways.  I just enabled the last one this past Friday and so far it only has data from Friday and this is Monday.  This is regarding the below link.  I can't tell from github if it took me to the correct page to report issues on this topic.

https://docs.microsoft.com/en-us/data-integration/gateway/service-gateway-performance

**Comment by DougKlopfenstein** [comment]
@SteveWest1 Thanks for your feedback. For product related issues and ideas, visit https://ideas.powerbi.com/forums/265200-power-bi?category_id=161724.

Closing the issue.
