### ISSUE TITLE
Check translation to Russian on this page! 

### ISSUE THREAD

**Issue by AndriyLyubimov** [MicrosoftDocs/data-integration#22]
Please re-check translation on this page: every terms are translated by Machine Translation incorrectly!
Что за белеберда в переводе? Что такое Кпуутилизатионперцентажесрешолд или Меморютилизатионперцентажесрешолд? Явно пропустили ошибки атоматизированного перевода.

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 3609538e-bb86-1026-ddd5-dabe93fddc7e
* Version Independent ID: 9dbd2442-7d03-5e24-0882-7a10cb2f71d7
* Content: [Управление кластерами с высоким уровнем доступности и балансировкой нагрузки для локального шлюза данных](https://docs.microsoft.com/ru-ru/data-integration/gateway/service-gateway-high-availability-clusters#feedback)
* Content Source: [data-integration/gateway/service-gateway-high-availability-clusters.md](https://github.com/MicrosoftDocs/data-integration-pr.ru-RU/blob/live/data-integration/gateway/service-gateway-high-availability-clusters.md)
* Technology: **on-premises-data-gateway**
* GitHub Login: @arthiriyer
* Microsoft Alias: **arthii**

**Comment by psholko** [comment]
+1

**Comment by DougKlopfenstein** [comment]
Thank you for your feedback. This is now under review and no further action is required at this time.
