### ISSUE TITLE
November 2019 release is missing

### ISSUE THREAD

**Issue by olyamusok** [MicrosoftDocs/data-integration#23]
Look like link for November 2019 release is missing. Most recent version installer link is for December.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 27fa3259-c8cf-bd35-7e6a-6f8a1f2a36cf
* Version Independent ID: 187906ab-5531-bce0-084c-d90e3c009c82
* Content: [Previous monthly updates to the on-premises data gateways](https://docs.microsoft.com/en-us/data-integration/gateway/service-gateway-monthly-updates)
* Content Source: [data-integration/gateway/service-gateway-monthly-updates.md](https://github.com/MicrosoftDocs/data-integration/blob/master/data-integration/gateway/service-gateway-monthly-updates.md)
* Technology: **on-premises-data-gateway**
* GitHub Login: @arthiriyer
* Microsoft Alias: **arthii**

**Comment by KumarVivek** [comment]
@olyamusok This is resolved now. Closing the issue.
