### ISSUE TITLE
Out of data screenshot

### ISSUE THREAD

**Issue by rwlpf** [MicrosoftDocs/data-integration#231]
This image is out of date when installing the standard data gateway this is not the screen the users see. 
![image](https://user-images.githubusercontent.com/919539/233575350-e78f7cde-29a6-40ce-a705-d81192af72c0.png)

The three items with the light blue background are *not* in the dialog box. This caused considerable confusion for one of our clients as they were following the documentation on this page and expected to see the same dialog boxes.

Can this be updated as soon as possible please. Note our customers do refer to documentation on a regular basis, and it is viewed as a very valuable resource.

Thanks
Robert

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5c51a10c-d90c-7690-0979-cd8ce37234c8
* Version Independent ID: 2da65f4c-f128-40b8-1a2b-5ae72c4252d6
* Content: [Install an on-premises data gateway](https://learn.microsoft.com/en-us/data-integration/gateway/service-gateway-install)
* Content Source: [data-integration/gateway/service-gateway-install.md](https://github.com/MicrosoftDocs/data-integration/blob/main/data-integration/gateway/service-gateway-install.md)
* Product: **on-premises-data-gateway**
* GitHub Login: @miquelladeboer
* Microsoft Alias: **mideboer**

**Comment by DougKlopfenstein** [comment]
Hi @rwlpf 

Thanks for the feedback!

Just did an install of the latest gateway version. This is what I see:

![image](https://user-images.githubusercontent.com/40473364/233677337-913759db-ba45-42c4-96e4-08908a019197.png)

Could you send an image of what they get when they install the gateway?

**Comment by DougKlopfenstein** [comment]
Is it possible that they accidentally installed the personal mode gateway? The screen for the personal mode gateway looks like this:

![image](https://user-images.githubusercontent.com/40473364/233686787-d635b801-feee-4a9c-b72e-229648d701f0.png)

**Comment by rwlpf** [comment]
Thanks for the screenshots.

Long story short, I asked the client whether they used the personal version, and they confirmed that it was the Standard version. That they downloaded the standard version and attempted the install it separately three times with the same result.

I have installed, recently (last week), the standard gateway, and we see the screen that you state is related to the personal gateway
Below is the screenshot from when we installed the "Standard Gateway", which is clear from the wording at the top. Also, the file name of the .exe file makes it very which file has been downloaded. When I downloaded the file, I ensured that I had downloaded the standard gateway.

![Datagatway](https://user-images.githubusercontent.com/919539/233786346-364182bb-eae7-46d8-85f6-4f7ebc956f01.jpg)

Next question I have, in this article - https://learn.microsoft.com/en-us/data-integration/gateway/service-gateway-app is they the standard or personal gateway in the screenshot? It appears to be the standard gateway based on the text at the top, yet it does look like the screenshot shown earlier for the standard gateway.

Please understand that my questions are to ensure I establish what I have done differently to ensure we have the correct gateway installed.

**Comment by DougKlopfenstein** [comment]
Accidentally closed, so I've reopened.

**Comment by rwlpf** [comment]
Just to confirm in all the instances referred to these are all new installations, done after downloading the lasts version of the standard gateway.

By doing a new installation the standard gateway on a Win 10 machine running in VmWare workstation I was able to reproduce the screens shown in the documentation. This is to say the screens I would expect to see, as per the documentation.

Note the other new installation the standard gateway on the following operating system - Windows (Windows Server 2022 Datacenter Azure Edition). Both of these installations are running an Azure VM's.  That to my mind should not make a difference yet the installation screen and screenshot above suggest that they are. Is that correct? My assumption is my client did the same and hence saw what have seen on the OS Windows (Windows Server 2022 Datacenter Azure Edition).  Where as using the OS Win 10 I get a different screens.

**Comment by nikkiwaghani** [comment]
Can you please open a ticket here: https://admin.powerplatform.microsoft.com/?

**Comment by DougKlopfenstein** [comment]
Closing because this is a product feedback issue instead of a documentation issue.

**Comment by rwlpf** [comment]
So there is an issue with the product? Which both myself and one of my
customers have noticed. So my best course of action is to leave a comment
on the page to that comments that under certain circumstances, what is
documented will *not be seen? *So causing the customer *considerable
confusion* as they have correctly installed the product, yet the
documentation does not reflect what they see?
