### ISSUE TITLE
Missing EvaluationContext in the QueryStartLog fields list

### ISSUE THREAD

**Issue by R1k91** [MicrosoftDocs/data-integration#261]
docs are out of date.
With July 23 gateway release a new field appeared in the QueryStartLog_* files.
it's called "EvaluationContext" but docs hasn't any clue about it.

I blogged what I found on customers here: https://perico-riccardo.medium.com/on-premises-data-gateway-evaluationcontext-92933d8f89dd

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4a144b27-04b6-5d42-9c9f-79bb4cc6730b
* Version Independent ID: 7b00f680-f3a8-3502-94b5-5ca37d36f432
* Content: [Monitor and optimize on-premises data gateway performance](https://learn.microsoft.com/en-us/data-integration/gateway/service-gateway-performance)
* Content Source: [data-integration/gateway/service-gateway-performance.md](https://github.com/MicrosoftDocs/data-integration/blob/main/data-integration/gateway/service-gateway-performance.md)
* Product: **on-premises-data-gateway**
* GitHub Login: @miquelladeboer
* Microsoft Alias: **mideboer**

**Comment by DougKlopfenstein** [comment]
Hi @R1k91 
Thanks for your feedback! Information about EvaluationContext has been added to the Query Start Report table.
