### ISSUE TITLE
Is virtual network (VNet) data gateway in Preview mode?

### ISSUE THREAD

**Issue by zakharRealogic** [MicrosoftDocs/data-integration#262]
This title confuses. The feature is not in Preview mode, however this article title tells that this is Preview. I haven't found any confirmation that VNet data gateways are in preview.
Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d47e61c8-a5b8-0a8b-06dd-c242a0acd06c
* Version Independent ID: e80385c1-b254-525d-b5ec-2b653e7763d8
* Content: [What is a virtual network (VNet) data gateway (Preview)](https://learn.microsoft.com/en-us/data-integration/vnet/overview)
* Content Source: [data-integration/vnet/overview.md](https://github.com/MicrosoftDocs/data-integration/blob/main/data-integration/vnet/overview.md)
* Service: **virtual-network-data-gateway**
* GitHub Login: @nikkiwaghani
* Microsoft Alias: **nikkiwaghani**

**Comment by DougKlopfenstein** [comment]
Hi @zakharRealogic 

VNet data gateways are currently in public preview.
