### ISSUE TITLE
Design and implementation of a Power Platform data gateway

### ISSUE THREAD

**Issue by NickyvVr** [MicrosoftDocs/data-integration#27]
I asked a question on the Power BI forum, is it possible to act on that? Or is it preferred to do it here?
You can find my question here: https://community.powerbi.com/t5/Service/Gateway-entries-for-Power-BI-Power-Automate-PowerApps/m-p/913320

The question is the following:
You install a Power Platform data gateway that you can manage on the Power Platform Admin center. 

Then you create different connections (or gateway entries) for Power BI on one side (in app.powerbi.com) and Power Automate and PowerApps (and LogicApps?) on the other side (either on flow.microsoft.com/ or make.powerapps.com/home). Is that correct?

So connections/gateway entries for Power Automate and PowerApps are shared. Is there a reason behind why it is designed that way? Will it stay that way or are there plans to change this? More a question directed at MSFT than the community, but maybe someone knows?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a055322-906d-2af9-14f9-79e2ac44265d
* Version Independent ID: 7b6c3a05-12ad-9d44-c00c-cb9e9c971eff
* Content: [What is an on-premises data gateway?](https://docs.microsoft.com/en-us/data-integration/gateway/service-gateway-onprem)
* Content Source: [data-integration/gateway/service-gateway-onprem.md](https://github.com/MicrosoftDocs/data-integration/blob/master/data-integration/gateway/service-gateway-onprem.md)
* Technology: **on-premises-data-gateway**
* GitHub Login: @arthiriyer
* Microsoft Alias: **arthii**

**Comment by NickyvVr** [comment]
Any feedback on this item?

**Comment by DougKlopfenstein** [comment]
@NickyvVr This platform is for documentation related issues. For product related issues and ideas, visit https://ideas.powerbi.com/forums/265200-power-bi?category_id=161724.

Closing the issue.
