### ISSUE TITLE
Where to go for support with Gateway issues?

### ISSUE THREAD

**Issue by NHasgreenb** [MicrosoftDocs/data-integration#277]
This page tries to explain how to "Restore, migrate, or take over a gateway in a non-default region" and shows a screenshot that provides no indication how you get there. (maybe because I'm using a corporate account / tenant).

This page also does not mention how to change the region
https://learn.microsoft.com/en-us/data-integration/gateway/service-gateway-app

**Comment by jonburchel** [comment]
Thanks @NHasgreenb for pointing this out. We have made the change now. #please-close
