### ISSUE TITLE
Problem with PBIT template

### ISSUE THREAD

**Issue by slopezv2** [MicrosoftDocs/data-integration#291]
Hi,

After testing the PBIT template with a November 2023 standard gateway data the data loading process just get stuck and I tried to cancel and restart loading with the same result: Stuck loading. 

Power BI Desktop version used: 2.123.742.0 64-bit (November 2023)

![Evidence](https://github.com/MicrosoftDocs/data-integration/assets/8518846/fd04b9da-3354-4f76-8e38-cf7332280396)
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4a144b27-04b6-5d42-9c9f-79bb4cc6730b
* Version Independent ID: 7b00f680-f3a8-3502-94b5-5ca37d36f432
* Content: [Monitor and optimize on-premises data gateway performance](https://learn.microsoft.com/en-us/data-integration/gateway/service-gateway-performance)
* Content Source: [data-integration/gateway/service-gateway-performance.md](https://github.com/MicrosoftDocs/data-integration/blob/main/data-integration/gateway/service-gateway-performance.md)
* Product: **on-premises-data-gateway**
* GitHub Login: @miquelladeboer
* Microsoft Alias: **mideboer**

**Comment by DougKlopfenstein** [comment]
Hi @slopezv2 
This issue seems to be product feedback or a request for product support rather than documentation feedback. For information about product feedback or customer support for Power BI Desktop, go to [Get help with Power BI](https://community.fabric.microsoft.com/t5/Desktop/bd-p/power-bi-designer).
