### ISSUE TITLE
Update for Fabric

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftDocs/data-integration#297]
Please update the note below for Fabric. Is this capability included with all or some Fabric capacities?

![image](https://github.com/MicrosoftDocs/data-integration/assets/1765732/b3fb4ab4-37ce-4b26-88ae-c08697d84013)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5091585c-6eae-176b-f97b-6e7bf5f18d3f
* Version Independent ID: ece61ded-aee6-c780-25ef-d5c57161df7b
* Content: [Use virtual network (VNet) data gateway and data sources in Power BI](https://learn.microsoft.com/en-us/data-integration/vnet/use-data-gateways-sources-power-bi)
* Content Source: [data-integration/vnet/use-data-gateways-sources-power-bi.md](https://github.com/MicrosoftDocs/data-integration/blob/main/data-integration/vnet/use-data-gateways-sources-power-bi.md)
* Service: **virtual-network-data-gateway**
* GitHub Login: @nikkiwaghani
* Microsoft Alias: **nikkiwaghani**

**Comment by jonburchel** [comment]
Thanks for helping us improve the docs, @VitalyMCT! I have updated the article in the PR referenced above. #please-close

**Comment by VitalyMCT** [comment]
@jonburchel Sorry, we are not seeing any PR references or an article update around this. Is it a publishing latency issue?

**Comment by jonburchel** [comment]
@VitalyMCT, apologies, the reference is for the internal private version of the repo that gets pushed out to the public version every few hours, so although I can see it here, you must not be able to see it if you aren't a Microsoft employee or a member of the right org on GitHub. It is live now though so you can check the article to confirm the note text changed now that we're no longer in preview, and mentions that all Fabric licenses support the VNet gateway.

**Comment by VitalyMCT** [comment]
@jonburchel Thank you. The change propagated to the public version now.
