### ISSUE TITLE
Release notes ("List of features released") are missing for "December 2023 update (3000.202.13)" 

### ISSUE THREAD

**Issue by TS-SC7** [MicrosoftDocs/data-integration#300]
When will the release notes ("List of features released") for "December 2023 update (3000.202.13)" be added to the page?

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 27fa3259-c8cf-bd35-7e6a-6f8a1f2a36cf
* Version Independent ID: 187906ab-5531-bce0-084c-d90e3c009c82
* Content: [Currently supported monthly updates to the on-premises data gateways](https://learn.microsoft.com/en-us/data-integration/gateway/service-gateway-monthly-updates)
* Content Source: [data-integration/gateway/service-gateway-monthly-updates.md](https://github.com/MicrosoftDocs/data-integration/blob/main/data-integration/gateway/service-gateway-monthly-updates.md)
* Product: **on-premises-data-gateway**
* GitHub Login: @miquelladeboer
* Microsoft Alias: **mideboer**

**Comment by JasonWHowell** [comment]
The blog hasn't been written yet, so the link isn't there for that reason. 
I'm not sure how involved it is to create the blog post for December 2023.

**Comment by jonburchel** [comment]
Hi @TS-SC7, and thanks for your question. This is updated now with the December update. #please-close

**Comment by TS-SC7** [comment]
Hi @jonburchel 

I don't see the release notes update on the live page, is it stuck in the pipe?

It currently looks like this:

December 2023 update (3000.202.13)
Download the latest versions:

Download the [latest on-premises data gateway](https://download.microsoft.com/download/D/A/1/DA1FDDB8-6DA8-4F50-B4D0-18019591E182/GatewayInstall.exe)
Download the [latest on-premises data gateway (personal mode)](https://download.microsoft.com/download/6/0/2/602A459E-E1A3-4FB9-B07F-FC2B60881900/On-premises%20data%20gateway%20(personal%20mode).exe)

But it should look similar to **this** after the release notes have been added (Note the list of features released link):

November 2023 update (3000.198.17)
**[List of features released](https://powerbi.microsoft.com/blog/on-premises-data-gateway-november-2023-release/)**
[Download the November 2023 version of on-premises data gateway](https://download.microsoft.com/download/D/A/1/DA1FDDB8-6DA8-4F50-B4D0-18019591E182/GatewayInstall-23-11.exe)
[Download the November 2023 version of on-premises data gateway (personal mode)](https://download.microsoft.com/download/6/0/2/602A459E-E1A3-4FB9-B07F-FC2B60881900/On-premises%20data%20gateway%20(personal%20mode)-23-11.exe)

Please advise?

Thanks

**Comment by TS-SC7** [comment]
#please-reopen

**Comment by TS-SC7** [comment]
FYI @jonburchel for comparison:

![image](https://github.com/MicrosoftDocs/data-integration/assets/155971584/642164e0-cf65-452e-9d02-d08e4a73a55e)

**Comment by jonburchel** [comment]
Hi @TS-SC7. There isn't a public list of features for December yet. If one becomes available I will add the link here, as well as January's. Even though we don't have release notes yet, I did update the doc with the January release now also.

**Comment by TS-SC7** [comment]
Thanks for the update @jonburchel 

Will there be release notes going forwards @nikkiwaghani ?

Reason for my checking for updates on this: Our Infosec team requires release notes for everything that we install/update.

Obviously eventually we will be forced into applying the update(s) due to the support policies of Azure, but it would be good if there were release notes available with each new version as it is released so that we can satisfy compliance requirements etc.

Also, it will notify us of any gotchas or known issues as well.

Thanks for your time on this, much appreciated.
Cheers
