### ISSUE TITLE
Requirements are out of date

### ISSUE THREAD

**Issue by hrrysckr** [MicrosoftDocs/data-integration#31]
Are the minimum requirements correct still? November's blog mentions this:

"We would be using .NET 4.8 framework for gateways February 2020 version or higher hence some of the operating systems we used to support may no longer be supported . More information about OS which will be supported here."
https://powerbi.microsoft.com/en-us/blog/on-premises-data-gateway-november-2019-update-is-now-available/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c51a10c-d90c-7690-0979-cd8ce37234c8
* Version Independent ID: 2da65f4c-f128-40b8-1a2b-5ae72c4252d6
* Content: [Install an on-premises data gateway](https://docs.microsoft.com/en-us/data-integration/gateway/service-gateway-install)
* Content Source: [data-integration/gateway/service-gateway-install.md](https://github.com/MicrosoftDocs/data-integration/blob/master/data-integration/gateway/service-gateway-install.md)
* Technology: **on-premises-data-gateway**
* GitHub Login: @arthiriyer
* Microsoft Alias: **arthii**

**Comment by DougKlopfenstein** [comment]
@hrrysckr Thanks for your feedback. Currently, .NET Framework 4.7.2 is required for Gateway release September 2019 and later. We've postponed the .NET 4.8 requirement to the future with no certain ETA as of yet.
