### ISSUE TITLE
A list of releases for integration?

### ISSUE THREAD

**Issue by mikaelsand** [MicrosoftDocs/data-integration#316]
This list is good and useful, but we need a datasource for releases, like an endpoint that lists the supported versions. This is very useful when automating scans for versions. We run a lot of gateways and it is hard to know what version is tha latest or even what version is supported.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 27fa3259-c8cf-bd35-7e6a-6f8a1f2a36cf
* Version Independent ID: 187906ab-5531-bce0-084c-d90e3c009c82
* Content: [Currently supported monthly updates to the on-premises data gateways](https://learn.microsoft.com/en-us/data-integration/gateway/service-gateway-monthly-updates)
* Content Source: [data-integration/gateway/service-gateway-monthly-updates.md](https://github.com/MicrosoftDocs/data-integration/blob/main/data-integration/gateway/service-gateway-monthly-updates.md)
* Service: **on-premises-data-gateway**
* GitHub Login: @miquelladeboer
* Microsoft Alias: **mideboer**

**Comment by JasonWHowell** [comment]
@mikaelsand  We don't have a system that lists versions on a server endpoint to check. Good idea. 

Please search and create the product ideas here: https://ideas.fabric.microsoft.com/?forum=2d80fd4a-16cb-4189-896b-e0dac5e08b41

I know it's manual, but the doc explains 6 months' worth of updates are supported.
> This article describes the last six updates for the on-premises data gateways and provides links for downloading any of these versions. These updates are the versions we support.

Thanks, Jason
#please-close
