### ISSUE TITLE
vnetgateways - Fabric F SKU

### ISSUE THREAD

**Issue by sha-k-anand** [MicrosoftDocs/data-integration#317]
This documentation does not clearly call out if vnetgateway are supported on Fabric F SKUs are not.  Can you please update the doc to clarify this ?  In my testing, i was able to successfully configure vnetgateway on F SKUs. 

Current Documentation
"Virtual network data gateways is a Premium and Embedded feature, and will be available only in Power BI Premium workspaces, 
Premium Per User (PPU), and Power BI Embedded for public preview"

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5091585c-6eae-176b-f97b-6e7bf5f18d3f
* Version Independent ID: ece61ded-aee6-c780-25ef-d5c57161df7b
* Content: [Use virtual network (VNet) data gateway and data sources in Power BI](https://learn.microsoft.com/en-us/data-integration/vnet/use-data-gateways-sources-power-bi)
* Content Source: [data-integration/vnet/use-data-gateways-sources-power-bi.md](https://github.com/MicrosoftDocs/data-integration/blob/main/data-integration/vnet/use-data-gateways-sources-power-bi.md)
* Service: **virtual-network-data-gateway**
* GitHub Login: @nikkiwaghani
* Microsoft Alias: **nikkiwaghani**

**Comment by VitalyMCT** [comment]
Yes, I've previously flagged the same issue at #297

**Comment by jonburchel** [comment]
Thanks for helping us improve the docs @sha-k-anand. I have addressed this in the PR referenced above now. #please-close
