### ISSUE TITLE
Are Conditional Access Policies Supported?

### ISSUE THREAD

**Issue by fulky** [MicrosoftDocs/data-integration#320]
[Enter feedback here]
Seeing some inconsistency in support for Conditional Access Policies.   The FAQ section (at the bottom) states they are not supported but in the same document it says they are https://learn.microsoft.com/en-us/data-integration/vnet/data-gateway-faqs#does-the-vnet-data-gateway-support-conditional-access-policies-

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0ee0e9bd-3051-ae24-e7c1-1dc6aa0c137c
* Version Independent ID: 4011df39-116e-dff0-3316-742bc994dc58
* Content: [Virtual network (VNet) data gateway FAQs](https://learn.microsoft.com/en-us/data-integration/vnet/data-gateway-faqs#does-the-vnet-data-gateway-support-conditional-access-policies-)
* Content Source: [data-integration/vnet/data-gateway-faqs.yml](https://github.com/MicrosoftDocs/data-integration/blob/main/data-integration/vnet/data-gateway-faqs.yml)
* Service: **virtual-network-data-gateway**
* GitHub Login: @nikkiwaghani
* Microsoft Alias: **nikkiwaghani**

**Comment by jonburchel** [comment]
Thanks for your feedback to help us improve the docs, @fulky. I confirmed the FAQ no longer incorrectly states CAPs are unsupported. I will close this issue out for now, but we can continue the discuss here if necessary, even after it is closed. #please-close
