### ISSUE TITLE
VNet Data Gateway Preview/Generally Available info

### ISSUE THREAD

**Issue by bpelikan** [MicrosoftDocs/data-integration#326]
Based on this announcement: [VNet Data Gateway for Fabric and Power BI is now Generally Available](https://powerbi.microsoft.com/en-us/blog/vnet-data-gateway-for-fabric-and-power-bi-is-now-generally-available/)
VNet Data Gateway is in Generally Available from February 1st 2024, but there is still information about the preview version in the documentation
![image](https://github.com/MicrosoftDocs/data-integration/assets/24376947/11ec41cc-1e8f-4e68-8593-c252bdc3ee25)

 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d47e61c8-a5b8-0a8b-06dd-c242a0acd06c
* Version Independent ID: e80385c1-b254-525d-b5ec-2b653e7763d8
* Content: [What is a virtual network (VNet) data gateway (Preview)](https://learn.microsoft.com/en-us/data-integration/vnet/overview)
* Content Source: [data-integration/vnet/overview.md](https://github.com/MicrosoftDocs/data-integration/blob/main/data-integration/vnet/overview.md)
* Service: **data-integration-gateways**
* Sub-service: **virtual-network-data-gateways**
* GitHub Login: @nikkiwaghani
* Microsoft Alias: **nikkiwaghani**

**Comment by JasonWHowell** [comment]
#assign:jonburchel

**Comment by jonburchel** [comment]
Thanks @bpelikan! I've updated the docs and it should be published on the next cycle later today. #please-close
