### ISSUE TITLE
It's not clear to a newcomer if the On-Premise Gateway is "passing through" credentials

### ISSUE THREAD

**Issue by Cornan** [MicrosoftDocs/data-integration#327]
It's not clear if the gateway is passing through existing credentials "as if" the requestor was accessing them from within the local network", and what type of credentials those must be.

For example, if we are using SQL Server authentication (user + password) on a WORKGROUP computer (not on a domain), can they be passed through the gateway?  Or is Windows Authentication required?

Similarly for file access.  This web page only mentions "credentials" in general terms.  It's also unclear what PBiegwservice is to be used for, even on a  high level - it's mentioned, but with no context.  

Again, not looking for "all the details", just something to aid understanding.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0c654ef3-6a36-2f86-9640-1585efabfd0a
* Version Independent ID: 2c3c6a6a-d095-f057-b225-dc1206b2d72a
* Content: [On-premises data gateway architecture](https://learn.microsoft.com/en-us/data-integration/gateway/service-gateway-onprem-indepth)
* Content Source: [data-integration/gateway/service-gateway-onprem-indepth.md](https://github.com/MicrosoftDocs/data-integration/blob/main/data-integration/gateway/service-gateway-onprem-indepth.md)
* Service: **data-integration-gateways**
* Sub-service: **on-premises-data-gateways**
* GitHub Login: @miquelladeboer
* Microsoft Alias: **mideboer**

**Comment by jonburchel** [comment]
Hi @Cornan, and thanks for your question. Yes, authentication happens from the local machine on which the gateway is installed directly, and while credentials are securely passed from the cloud to the gateway for its use, the gateway itself logs in locally with them. #please-close
