### ISSUE TITLE
Page needs to be updated: License capacity is now also required when creating new virtual network data gateway

### ISSUE THREAD

**Issue by Shuwi75** [MicrosoftDocs/data-integration#330]
The UI has changed, the selection of a license capacity is now also required. 
Thank you for your support, 
Jeroen

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e5867016-6164-3563-47bb-1a7b93dc2caf
* Version Independent ID: be22c980-4684-8837-9123-1bcf98e75f06
* Content: [Create virtual network (VNet) data gateways](https://learn.microsoft.com/en-us/data-integration/vnet/create-data-gateways)
* Content Source: [data-integration/vnet/create-data-gateways.md](https://github.com/MicrosoftDocs/data-integration/blob/main/data-integration/vnet/create-data-gateways.md)
* Service: **data-integration-gateways**
* Sub-service: **virtual-network-data-gateways**
* GitHub Login: @nikkiwaghani
* Microsoft Alias: **nikkiwaghani**

**Comment by jonburchel** [comment]
Thank you @Shuwi75 for your feedback to help us improve the docs! This page does now mention the required selection of license capacity in Step 3, part 5. #please-close
