### ISSUE TITLE
The list of public domains for Dataflow Gen1 and Gen2 is incomplete or inaccurate

### ISSUE THREAD

**Issue by AlexGorbunov-AU** [MicrosoftDocs/data-integration#334]
Hi team,
the list of ports and domains for Dataflow Gen1 and Gen2 seems to be incomplete.
We are facing the issue when the traffic between the Data Gateway and the Fabric Data Warehouse is partially blocked.
After some testing we identified a few addresses which are not listed in the document:
1.	**\<someSortOfID\>.pbidedicated.windows.net**
2.	**\<someSortOfID\>.privatelink.pbidedicated.windows.net**

The document requires ***.datawarehouse.pbidedicated.windows.net** to be allowed, but not the other variations.
As a result the traffic is getting blocked by organisational firewall policies.
Can you please double check and confirm if the domain pbidedicated.windows.net listed correctly?
Going forward - will there be any similar issues with the datawarehouse.fabric.microsoft.com?
Do we need to allow some of these:
1) ***.fabric.microsoft.com** ?
2) ***.privatelink.fabric.microsoft.com** ?

Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f4daef9a-341c-696a-1d19-de05ffd67588
* Version Independent ID: 7cd18c28-7227-488a-aa28-6b869058e715
* Content: [Adjust communication settings for the on-premises data gateway](https://learn.microsoft.com/en-us/data-integration/gateway/service-gateway-communication#opening-extra-ports-for-dataflow-gen1-and-gen2-using-opdg)
* Content Source: [data-integration/gateway/service-gateway-communication.md](https://github.com/MicrosoftDocs/data-integration/blob/main/data-integration/gateway/service-gateway-communication.md)
* Service: **data-integration-gateways**
* Sub-service: **on-premises-data-gateways**
* GitHub Login: @miquelladeboer
* Microsoft Alias: **mideboer**

**Comment by jonburchel** [comment]
Hi @AlexGorbunov-AU, and thanks for your question. In addition to specific ports and sites, you must also add the [Service Tags mentioned in the article](https://learn.microsoft.com/en-us/data-integration/gateway/service-gateway-communication#service-tags), which will selectively grant access to other destinations as required by the service. This should resolve those other sites you found that were requiring access. 

#please-close
