### ISSUE TITLE
Spool Storage

### ISSUE THREAD

**Issue by TePeBoxer** [MicrosoftDocs/data-integration#34]
You should add that the spool storage is drive C:
C:\Users\PBIEgwService\AppData\Local\Microsoft\On-premises data gateway\Spooler. This needs to be monitored so it's not running full...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c654ef3-6a36-2f86-9640-1585efabfd0a
* Version Independent ID: 2c3c6a6a-d095-f057-b225-dc1206b2d72a
* Content: [On-premises data gateway architecture](https://docs.microsoft.com/en-us/data-integration/gateway/service-gateway-onprem-indepth#feedback)
* Content Source: [data-integration/gateway/service-gateway-onprem-indepth.md](https://github.com/MicrosoftDocs/data-integration/blob/master/data-integration/gateway/service-gateway-onprem-indepth.md)
* Technology: **on-premises-data-gateway**
* GitHub Login: @arthiriyer
* Microsoft Alias: **arthii**

**Comment by DougKlopfenstein** [comment]
Hi @TePeBoxer 
This information has been added here - https://docs.microsoft.com/en-us/data-integration/gateway/service-gateway-performance#monitoring-spool-storage
