### ISSUE TITLE
VNet Data Gateway Supported Sources - PostgreSQL

### ISSUE THREAD

**Issue by mtsolekas** [MicrosoftDocs/data-integration#340]
The latest documentation regarding the supported data sources has no mention of Azure Managed PostgreSQL and other Managed databases aside from Azure SQL in the secure VNet access segment. The same document, 2 months prior, had the following content, showing PostgreSQL being clearly supported:
```
In the current release, VNet data gateways support connectivity to the following data sources:

    Azure SQL
    Azure Synapse Analytics
    Azure Databricks
    Azure Data Explorer (Kusto)
    Azure Table Storage
    Azure Blob Storage
    Azure HDInsight (Spark)
    Azure Data Lake (Gen2)
    Cosmos DB
    Azure SQL Managed Instance (MI)
    Snowflake on Azure
    PostgreSQL
    SQL Server
    And more—all data sources shown when creating a connection are supported
```

In the latest document PostgreSQL has been moved to the public endpoint segment, which as I understand it, means it does **NOT** support VNet gateway integration.

Could there be some clarification about Azure Managed PostgreSQL and its support?

Below are links to the current and older documents:
- 21 Dec [Supported Azure data services](https://github.com/MicrosoftDocs/data-integration/blob/a2974c17db37bbc6e6a7347722c3c46a4ef9a796/data-integration/vnet/use-data-gateways-sources-power-bi.md#supported-azure-data-services)
- Now [Supported Azure data services](https://github.com/MicrosoftDocs/data-integration/blob/main/data-integration/vnet/use-data-gateways-sources-power-bi.md#supported-azure-data-services)

**Comment by jonburchel** [comment]
Hi @mtsolekas, and thanks for your question. I confirmed PostgreSQL is listed there under **Sources supported with public endpoints**. #please-close
