### ISSUE TITLE
Combining data source types

### ISSUE THREAD

**Issue by asocorrocognex** [MicrosoftDocs/data-integration#38]
Hi, is there a limitation about combining online with on-premise data sources in the same dataflow?  I am getting a credentials error that does not happen when I separate them.  Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 22e57321-1e82-b45c-f628-4044559882d2
* Version Independent ID: c8b34c42-6a20-0cd6-be82-1719e1de0be4
* Content: [Connect to data sources for dataflows](https://docs.microsoft.com/en-us/data-integration/dataflows/dataflows-data-sources#feedback)
* Content Source: [data-integration/dataflows/dataflows-data-sources.md](https://github.com/MicrosoftDocs/data-integration/blob/master/data-integration/dataflows/dataflows-data-sources.md)
* Service: **dataflows**
* GitHub Login: @bensack
* Microsoft Alias: **bensack**

**Comment by DougKlopfenstein** [comment]
Hi @asocorrocognex 
Thanks for your dedication to our documentation. Unfortunately, at this time we have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again.
