### ISSUE TITLE
Join limitations

### ISSUE THREAD

**Issue by asocorrocognex** [MicrosoftDocs/data-integration#39]
Hi, could you please elaborate on the bullet in the Limitations and Considerations section that says "A linked entity can't be joined with a regular entity that gets its data from an on-premises data source." Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 884ff436-66bb-afce-de9d-9a8d9748740e
* Version Independent ID: 583e33a5-4cd1-037c-f089-dca3f5064094
* Content: [Link entities between dataflows](https://docs.microsoft.com/en-us/data-integration/dataflows/dataflows-linked-entities)
* Content Source: [data-integration/dataflows/dataflows-linked-entities.md](https://github.com/MicrosoftDocs/data-integration/blob/master/data-integration/dataflows/dataflows-linked-entities.md)
* Service: **dataflows**
* GitHub Login: @bensack
* Microsoft Alias: **bensack**

**Comment by DougKlopfenstein** [comment]
Hi @asocorrocognex 
Thanks for your dedication to our documentation. Unfortunately, at this time we have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again.
