### ISSUE TITLE
Using Windows Authentication

### ISSUE THREAD

**Issue by amasse3** [MicrosoftDocs/data-integration#4]
3rd bullet under Related considerations:

> If you're planning to use Windows authentication, make sure you install the gateway on a computer that's a member of the same Azure Active Directory (Azure AD) environment as the data sources.

Should this say Active Directory (AD) environment?

**Comment by mgblythe** [comment]
Thanks @amasse3, makes sense to me, but adding @arthiriyer to confirm.

**Comment by arthiriyer** [comment]
@mgblythe - agree

**Comment by mgblythe** [comment]
This is now fixed in the doc, so closing out.
