### ISSUE TITLE
how to delete gateway

### ISSUE THREAD

**Issue by ballever** [MicrosoftDocs/data-integration#41]
I don't remenber key and also forget where I login primary gateway , how to delete that

Something went wrong

We could not remove this gateway because it is the primary gateway within a cluster that has other gateway instances. Please remove other gateway instances from this cluster before removing the primary gateway.
Please try again later or contact support. If you contact support, please provide these details.Show technical details
Get help
Copy
Close

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 20180bfa-f4ab-224a-d089-58a06dbf4ac3
* Version Independent ID: f4ab3a3c-397d-01d1-f6d2-05e9085770a1
* Content: [管理本地数据网关](https://docs.microsoft.com/zh-cn/data-integration/gateway/service-gateway-manage#feedback)
* Content Source: [data-integration/gateway/service-gateway-manage.md](https://github.com/MicrosoftDocs/data-integration-pr.zh-CN/blob/live/data-integration/gateway/service-gateway-manage.md)
* Technology: **on-premises-data-gateway**
* GitHub Login: @arthiriyer
* Microsoft Alias: **arthii**

**Comment by DougKlopfenstein** [comment]
@ballever Thanks for your feedback. For product related issues and ideas, visit https://ideas.powerbi.com/forums/265200-power-bi?category_id=161724.

Closing the issue.
