### ISSUE TITLE
There seems to be no way to set the service account back to NT SERVICE\PBIEgwService

### ISSUE THREAD

**Issue by ThirstyAdmin** [MicrosoftDocs/data-integration#42]
Hello, 

There seems to be no way to properly switch the account the on premise data gateway windows service runs under back to NT SERVICE\PBIEgwService, after switching it to a domain account. I have tried the following to get this to work. 

1. Instead of using the on premise data gateway software to switch the service back i just updated the windows service itself back to NT SERVICE\PBIEgwService and restarted the service. But the gateway is then no longer able to connect and is in a broken state. 

2. Tried to use the on premise data gateway software to switch the service back but it only accepts domain accounts. Obviously i don't know what the NT SERVICE\PBIEgwService password is, nor should I. But i'd like to switch the service back to what it was originally. 

3. I've tried uninstalling the gateway software and reinstalling it. this does change the service back to using NT SERVICE\PBIEgwGateway but the gateway never comes back online until i switch it back to the domain account.

**Comment by DougKlopfenstein** [comment]
@ThirstyAdmin Thanks for your feedback. For product related issues and ideas, visit https://ideas.powerbi.com/forums/265200-power-bi?category_id=161724.

Closing the issue.
