### ISSUE TITLE
only SystemCounterAggregationReport is generating

### ISSUE THREAD

**Issue by nodenks** [MicrosoftDocs/data-integration#44]
Hi,
I tried the following instruction on my on-prem gateway and only one file SystemCounterAggregationReport is generated. How can I troubleshoot it? I have the latest version of the on-prem gateway.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a144b27-04b6-5d42-9c9f-79bb4cc6730b
* Version Independent ID: 7b00f680-f3a8-3502-94b5-5ca37d36f432
* Content: [Monitor and optimize on-premises data gateway performance](https://docs.microsoft.com/en-us/data-integration/gateway/service-gateway-performance#feedback)
* Content Source: [data-integration/gateway/service-gateway-performance.md](https://github.com/MicrosoftDocs/data-integration/blob/master/data-integration/gateway/service-gateway-performance.md)
* Technology: **on-premises-data-gateway**
* GitHub Login: @arthiriyer
* Microsoft Alias: **arthii**

**Comment by DougKlopfenstein** [comment]
@nodenks Thanks for your feedback. For product related issues and ideas, visit https://ideas.powerbi.com/forums/265200-power-bi?category_id=161724.

Closing the issue.
