### ISSUE TITLE
Suggestions for improvement

### ISSUE THREAD

**Issue by NeilMacMullen** [MicrosoftDocs/data-integration#48]
* It would help if the first paragraph made it clear you were talking about a page in the ONLINE app.powerbi.com -  I wasted 20 minutes trying to find this in PowerBi desktop.  The screen clip is really insufficient to locate the appropriate option in context (to me it looks like a screen cap of the LEFT hand side of the desktop app rather than the RIGHT hand side of the web app. 
* Personal gateway just seems not to work, full stop (at least I never see it registered.
* It should be made clear whether you need to leave the gateway app open in order for it to work.  The presence of the big "CLOSE" button in the bottom right where a "NEXT" button would normally be implies that closing it is _required_ for the gateway to function.  (I assume it's running as a service but that could be laid out explicitly)
* The big undocumented "gotcha" that exacerbates the confusion around all of these is that the "Manage gateways" page on app.powerbi.com DOES NOT REFRESH unless  you refresh the entire page :-(  I.e. you will continue to see an empty gateway list no matter how may times you go to "settings-&gt;Manage Gateways"  until you hit F5 in the browser.  This makes it appear that all the previous instructions steps are failed.
* Slightly amusing that the warning "manage gateways will not show up until you are an admin" appears before the section on managing admins which would appear to put the user in a bit of a catch-22.   (Yes I know you become an admin by creating a gateway but when you're not seeing any gateways in the list because of the behaviour above and you're assuming that somehow the admin-allocation has gone wrong locally, this warning seems like it's designed as a wind-up ;-)  )   

Perhaps these problems are due to me using the "New look" UI but it's frustrating that something that should "just work" in a couple of minutes requires an hour of floundering around before stumbling on the right sequence.

I would also suggest that this documentation suffers from the usual MS documentation structural issue of describing all the bits individually but making it quite unclear how to put them together.  Why not take a more task-based approach?  I'd bet 90% of users setting up a gateway fall into a couple of scenarios.... "As a data-analyst I want to be able to share and update a new csv file on a scheduled basis...."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 20180bfa-f4ab-224a-d089-58a06dbf4ac3
* Version Independent ID: f4ab3a3c-397d-01d1-f6d2-05e9085770a1
* Content: [Manage an on-premises data gateway](https://docs.microsoft.com/en-us/data-integration/gateway/service-gateway-manage)
* Content Source: [data-integration/gateway/service-gateway-manage.md](https://github.com/MicrosoftDocs/data-integration/blob/master/data-integration/gateway/service-gateway-manage.md)
* Technology: **on-premises-data-gateway**
* GitHub Login: @arthiriyer
* Microsoft Alias: **arthii**

**Comment by DougKlopfenstein** [comment]
Hi @NeilMacMullen 
Thanks for your feedback! Unfortunately, at this time we have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again.
