### ISSUE TITLE
This is not the "general content"

### ISSUE THREAD

**Issue by ewillman** [MicrosoftDocs/data-integration#5]
The preamble to this article states "We recently revised the on-premises data gateway docs. We split them into content that's specific to Power BI and general content that applies to all services that the gateway supports. You're currently in the general content." -- However, despite that Note saying that I am "currently in the general content.", this article only describes how to manage a gateway cluster in Power BI.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3609538e-bb86-1026-ddd5-dabe93fddc7e
* Version Independent ID: 9dbd2442-7d03-5e24-0882-7a10cb2f71d7
* Content: [Manage on-premises data gateway high-availability clusters and load balancing](https://docs.microsoft.com/en-us/data-integration/gateway/service-gateway-high-availability-clusters)
* Content Source: [data-integration/gateway/service-gateway-high-availability-clusters.md](https://github.com/MicrosoftDocs/data-integration/blob/master/data-integration/gateway/service-gateway-high-availability-clusters.md)
* Service: **powerbi**
* Sub-service: **powerbi-gateways**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by mgblythe** [comment]
Thanks @ewillman, you got me there :-). Right now our examples in the general content are still from Power BI, but we'll add other examples as we go. Which are most interesting to you?

**Comment by bengimblett** [comment]
Hi - i would also concur to the point above. The article suggests that you can change the Load Balancing behavior for the general OPDG - but in fact the example is only for PowerBI. I've looked at the installed product, the azure resource and the PowerShell and nowhere does it appear possible to change the behavior as suggested in the comment "You can choose to let traffic be distributed evenly across gateways in a cluster. "

**Comment by bengimblett** [comment]
Can anyone clarify ? Right now it looks like the "load balancing" is only possible on the powerBI version and if so the docs should be amended

**Comment by mgblythe** [comment]
@arthiriyer - can you clarify whether you can load balance with services other than Power BI?

**Comment by dgrospelier** [comment]
Any updates regarding the way to configure load balancing of the gateway with Azure for example? We are using the gateway with Logic Apps and there is no configuration settings in Azure to specify the load-balancing behavior.

**Comment by arthiriyer** [comment]
Hello- you can set up load balancing either from Power BI  or use PowerShell scripts https://docs.microsoft.com/en-us/powershell/module/datagateway/set-datagatewaycluster?view=datagateway-ps
We are working on a gateway management experience on the power platform admin center which will provide a standard experience across applications using gateways- unfortunately these configuration feature isn't available yet but we are actively working on making these available.
https://docs.microsoft.com/en-us/power-platform/admin/onpremises-data-gateway-management

**Comment by arthiriyer** [comment]
#please-close
