### ISSUE TITLE
Pls clarify requirements for sign-in account and security regarding authentication against the service / service bus

### ISSUE THREAD

**Issue by mpoeckl** [MicrosoftDocs/data-integration#50]
What happens if the login that was used to registered the gateway with the service is decommissioned (login/user is deleted/disabled in AAD)? Is the gateway still able to connect to the service? 
Does the gateway use the sign-in credentials provided during configuration to connect to the service or another mechanism to authenticate against the service / service bus? 
How are the credentials that the gateway uses for connecting to the service through service bus stored? Are they secured/encrypted (what type of encryption)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c654ef3-6a36-2f86-9640-1585efabfd0a
* Version Independent ID: 2c3c6a6a-d095-f057-b225-dc1206b2d72a
* Content: [On-premises data gateway architecture](https://docs.microsoft.com/en-us/data-integration/gateway/service-gateway-onprem-indepth#sign-in-account)
* Content Source: [data-integration/gateway/service-gateway-onprem-indepth.md](https://github.com/MicrosoftDocs/data-integration/blob/master/data-integration/gateway/service-gateway-onprem-indepth.md)
* Technology: **on-premises-data-gateway**
* GitHub Login: @arthiriyer
* Microsoft Alias: **arthii**

**Comment by DougKlopfenstein** [comment]
Hi @mpoeckl -

Thanks for your dedication to our documentation. Unfortunately, at this time we have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
