### ISSUE TITLE
Publishing Report to PBI Service

### ISSUE THREAD

**Issue by HairyDrumroll** [MicrosoftDocs/data-integration#55]
It might be useful to include in the documentation a description of how to publish this report to the Power BI service. It's not straight forward as the log folder needs to be configured in the Gateway - something I haven't yet figured out how to do.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a144b27-04b6-5d42-9c9f-79bb4cc6730b
* Version Independent ID: 7b00f680-f3a8-3502-94b5-5ca37d36f432
* Content: [Monitor and optimize on-premises data gateway performance](https://docs.microsoft.com/en-us/data-integration/gateway/service-gateway-performance)
* Content Source: [data-integration/gateway/service-gateway-performance.md](https://github.com/MicrosoftDocs/data-integration/blob/master/data-integration/gateway/service-gateway-performance.md)
* Technology: **on-premises-data-gateway**
* GitHub Login: @arthiriyer
* Microsoft Alias: **arthii**

**Comment by arthiriyer** [comment]
@HairyDrumroll publishing this report is similar to a report connecting to a folder data source. The log folder configuration is explained in the docs using ReportFilePath config value

**Comment by HairyDrumroll** [comment]
Yeah, so include that in the documentation. 
Maybe a link to the documentation you've referred to.

**Comment by JasonWHowell** [comment]
@DougKlopfenstein might be an easy fix in the doc

**Comment by DougKlopfenstein** [comment]
Hi @HairyDrumroll 
Thanks for your feedback! I believe this issue is now covered by [Gateway performance monitoring (public preview)](https://learn.microsoft.com/data-integration/gateway/service-gateway-performance#gateway-performance-monitoring-public-preview) and [Visualize gateway performance](https://learn.microsoft.com/data-integration/gateway/service-gateway-performance#visualize-gateway-performance). We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know.

**Comment by HarryDriscollTWE** [comment]
I think I'm missing something here. If I open the PBI template file provided under [Visualize gateway performance](https://learn.microsoft.com/data-integration/gateway/service-gateway-performance#visualize-gateway-performance) it prompts for the path to the log folder. But the log folder is on the gateway server's C drive, not mine. And if I publish the report then that path on the server's C drive needs to be shared and available through the gateway. Or have I missed a step in the instructions?
