### ISSUE TITLE
Can we use both Gateways in a same application

### ISSUE THREAD

**Issue by jishadshajahan** [MicrosoftDocs/data-integration#56]
Can we use both Gateways in a same application

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c51a10c-d90c-7690-0979-cd8ce37234c8
* Version Independent ID: 2da65f4c-f128-40b8-1a2b-5ae72c4252d6
* Content: [Install an on-premises data gateway](https://docs.microsoft.com/en-us/data-integration/gateway/service-gateway-install#feedback)
* Content Source: [data-integration/gateway/service-gateway-install.md](https://github.com/MicrosoftDocs/data-integration/blob/master/data-integration/gateway/service-gateway-install.md)
* Technology: **on-premises-data-gateway**
* GitHub Login: @arthiriyer
* Microsoft Alias: **arthii**

**Comment by arthiriyer** [comment]
@jishadshajahan what do you mean by "application" here?

**Comment by DougKlopfenstein** [comment]
Hi @jishadshajahan -
This issue has been closed due to lack of information. If you have more information to provide, please reopen this issue.
