### ISSUE TITLE
Clarify a few points

### ISSUE THREAD

**Issue by ElectricLlama** [MicrosoftDocs/data-integration#57]
As per here https://stackoverflow.com/questions/61729744/powerbi-gateway-load-balancing

1. When a new gateway is installed to the cluster, does it duplicate connections and credentials from the other gateway
2. Do gateways have to be the same version?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3609538e-bb86-1026-ddd5-dabe93fddc7e
* Version Independent ID: 9dbd2442-7d03-5e24-0882-7a10cb2f71d7
* Content: [Manage on-premises data gateway high-availability clusters and load balancing](https://docs.microsoft.com/en-us/data-integration/gateway/service-gateway-high-availability-clusters)
* Content Source: [data-integration/gateway/service-gateway-high-availability-clusters.md](https://github.com/MicrosoftDocs/data-integration/blob/master/data-integration/gateway/service-gateway-high-availability-clusters.md)
* Technology: **on-premises-data-gateway**
* GitHub Login: @arthiriyer
* Microsoft Alias: **arthii**

**Comment by arthiriyer** [comment]
The connections and credentials are stored as metdata at the cluster level instead of a gateway member level.
Please make sure the gateway members within a cluster are running the same gateway version as different versions could cause unexpected failures based on supported functionality

**Comment by DougKlopfenstein** [comment]
@ElectricLlama Thanks for your feedback. Since your questions are answered, I'm closing this issue.

**Comment by ElectricLlama** [comment]
Thanks Guys!
