### ISSUE TITLE
Automate installation and configuration of Gateway?

### ISSUE THREAD

**Issue by craigtp** [MicrosoftDocs/data-integration#6]
Is it possible to automate/script the installation and configuration of the PowerBI Gateway such that it can be completely installed and configured without human intervention?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c51a10c-d90c-7690-0979-cd8ce37234c8
* Version Independent ID: 2da65f4c-f128-40b8-1a2b-5ae72c4252d6
* Content: [Install an on-premises data gateway](https://docs.microsoft.com/en-us/data-integration/gateway/service-gateway-install)
* Content Source: [data-integration/gateway/service-gateway-install.md](https://github.com/MicrosoftDocs/data-integration/blob/master/data-integration/gateway/service-gateway-install.md)
* Service: **powerbi**
* Sub-service: **powerbi-gateway**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by mgblythe** [comment]
@craigtp - I don't think so, but I'm adding @arthiriyer to confirm.

**Comment by arthiriyer** [comment]
@craigtp- we are working on a cmd prompt install of gateway - we are hoping to have this available by the end of this year.

**Comment by rojomisin** [comment]
this is a huge gap in automating installs, real pain point, please hurry.
