### ISSUE TITLE
Documentation not accurate - out of sync with latest updates

### ISSUE THREAD

**Issue by haider392** [MicrosoftDocs/data-integration#60]
As per the doc, there is this instruction"Additionally, for the gateway to connect to cloud data sources through a proxy, update the following file: C:\Program Files\On-premises data gateway\Microsoft.Mashup.Container.NetFX45.exe.config."

This file no longer is available/included when you install a gateway  C:\Program Files\On-premises data gateway\Microsoft.Mashup.Container.NetFX45.exe.config.

Please confirm with PG and update documentation as it is misleading. We had a customer who referred this and questioned the accuracy of documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac8472eb-e13f-bbb0-698c-8faa13701ad8
* Version Independent ID: f30533a4-65a0-85f9-bcb1-4c96b307cd76
* Content: [Configure proxy settings for the on-premises data gateway](https://docs.microsoft.com/en-us/data-integration/gateway/service-gateway-proxy)
* Content Source: [data-integration/gateway/service-gateway-proxy.md](https://github.com/MicrosoftDocs/data-integration/blob/master/data-integration/gateway/service-gateway-proxy.md)
* Technology: **on-premises-data-gateway**
* GitHub Login: @arthiriyer
* Microsoft Alias: **arthii**

**Comment by DougKlopfenstein** [comment]
@haider392 Thanks for your feedback. The documentation has been updated to show the new location of the config file, as well as the release when it was changed (for those using an older version of the gateway).
