### ISSUE TITLE
Error refreshing via PBI Desktop

### ISSUE THREAD

**Issue by rhalabi** [MicrosoftDocs/data-integration#61]
I downloaded the template file and pointed to my report folder on my enterprise gateway.  When I PBI Desktop connects and tries to pull data on first load I get this error. Anyone know why or how to fix?  I have enabled the TRUE values and files exist in the report folder.

![image](https://user-images.githubusercontent.com/53341216/86151455-5a538200-bac4-11ea-830f-f5b2b9b713d7.png)

**Comment by DougKlopfenstein** [comment]
Hi @rhalabi -
Thanks for your feedback. This seems to be product feedback or a request for product support. For information about product feedback or customer support for Power BI, go to [Power BI Support](https://powerbi.microsoft.com/support/).
