### ISSUE TITLE
Outdated UI flow?

### ISSUE THREAD

**Issue by aceccare** [MicrosoftDocs/data-integration#62]
I believe this is not the current workflow anymore - when I click on my gateway I do not see the remove option.

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 20180bfa-f4ab-224a-d089-58a06dbf4ac3
* Version Independent ID: f4ab3a3c-397d-01d1-f6d2-05e9085770a1
* Content: [Manage an on-premises data gateway](https://docs.microsoft.com/en-us/data-integration/gateway/service-gateway-manage)
* Content Source: [data-integration/gateway/service-gateway-manage.md](https://github.com/MicrosoftDocs/data-integration/blob/master/data-integration/gateway/service-gateway-manage.md)
* Technology: **on-premises-data-gateway**
* GitHub Login: @arthiriyer
* Microsoft Alias: **arthii**

**Comment by DougKlopfenstein** [comment]
@aceccare Are you clicking on the ellipses on the right side of grayed-out area around the icon name as shown in the figure in the article? The remove option is still there.

**Comment by DougKlopfenstein** [comment]
Hi @aceccare -
This issue has been closed due to lack of information. If you have more information to provide, please reopen this issue.
