### ISSUE TITLE
Include more detail for how to add owners to a gateway with PowerShell

### ISSUE THREAD

**Issue by smokedlinq** [MicrosoftDocs/data-integration#65]
> Question: Can the person who sets up the gateway in the Azure portal be different from the one who installs that gateway?
> Answer: Yes, you must use PowerShell to add other owners to the same gateway. These users can create the gateway in the Azure portal. However, they should connect to the portal and the gateway by using the same tenant.

For the question, more guidance is needed. If this can be done with PowerShell, a link or example would be helpful to show how.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c093e8d2-49bb-cf51-02a8-d7792913a5ad
* Version Independent ID: 8fe1e76c-37e2-c6a8-4667-6578164d5b1e
* Content: [On-premises data gateway FAQ](https://docs.microsoft.com/en-us/data-integration/gateway/service-gateway-onprem-faq)
* Content Source: [data-integration/gateway/service-gateway-onprem-faq.md](https://github.com/MicrosoftDocs/data-integration/blob/master/data-integration/gateway/service-gateway-onprem-faq.md)
* Technology: **on-premises-data-gateway**
* GitHub Login: @arthiriyer
* Microsoft Alias: **arthii**

**Comment by smokedlinq** [comment]
For those looking for this information, first `Install-Module DataGateway` module and then use this command:

## Get GatewayClusterId

``` powershell
Get-DataGatewayCluster -RegionKey $RegionKey -Scope Individual
```

## Delegate Admin Role to Gateway Cluster

``` powershell
Add-DataGatewayClusterUser -GatewayClusterId $GatewayClusterId -PrincipalObjectId $AzureADUser -Role Admin -Scope Individual -RegionKey $RegionKey
```

**Comment by JasonWHowell** [comment]
Sorry, we are slow to triage these issues. It appears the FAQ has been updated, and this is no longer a common scenario that needs the PowerShell workaround. Closing as-is.
