### ISSUE TITLE
Payload Limit Confusion

### ISSUE THREAD

**Issue by tstooke** [MicrosoftDocs/data-integration#67]
This page indicates a "2MB" payload limit for Logic Apps; however, this other [page for the File System connector](https://docs.microsoft.com/en-us/connectors/filesystem/) indicates 20MB.  Which page is correct?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a055322-906d-2af9-14f9-79e2ac44265d
* Version Independent ID: 7b6c3a05-12ad-9d44-c00c-cb9e9c971eff
* Content: [What is an on-premises data gateway?](https://docs.microsoft.com/en-us/data-integration/gateway/service-gateway-onprem#considerations)
* Content Source: [data-integration/gateway/service-gateway-onprem.md](https://github.com/MicrosoftDocs/data-integration/blob/master/data-integration/gateway/service-gateway-onprem.md)
* Technology: **on-premises-data-gateway**
* GitHub Login: @arthiriyer
* Microsoft Alias: **arthii**

**Comment by KonTheCat** [comment]
The 20 MB page is correct, per testing, and this: 
https://feedback.azure.com/forums/287593-logic-apps/suggestions/20158219-file-system-connector-maximum-size-increased-above

**Comment by JasonWHowell** [comment]
Same as #68

**Comment by JasonWHowell** [comment]
Same issue in #68 #67 and #17

**Comment by DougKlopfenstein** [comment]
Hi @tstooke 
Thanks for the feedback. This issue has finally been resolved - [Considerations](https://docs.microsoft.com/data-integration/gateway/service-gateway-onprem#considerations)
