### ISSUE TITLE
payload limits may be incorrect

### ISSUE THREAD

**Issue by KonTheCat** [MicrosoftDocs/data-integration#68]
Hi, 

Please review the below:
Write operations have a 2-MB payload limit.
Read operations have a 2-MB request limit and an 8-MB compressed data response limit.

I think these limits are not correct, it is my understanding that the limit is now 20 MB for writes and 35 for reads. 
https://feedback.azure.com/forums/287593-logic-apps/suggestions/20158219-file-system-connector-maximum-size-increased-above

Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a055322-906d-2af9-14f9-79e2ac44265d
* Version Independent ID: 7b6c3a05-12ad-9d44-c00c-cb9e9c971eff
* Content: [What is an on-premises data gateway?](https://docs.microsoft.com/en-us/data-integration/gateway/service-gateway-onprem#considerations)
* Content Source: [data-integration/gateway/service-gateway-onprem.md](https://github.com/MicrosoftDocs/data-integration/blob/master/data-integration/gateway/service-gateway-onprem.md)
* Technology: **on-premises-data-gateway**
* GitHub Login: @arthiriyer
* Microsoft Alias: **arthii**

**Comment by JasonWHowell** [comment]
Same issue in #68 #67 and #17

**Comment by DougKlopfenstein** [comment]
Hi @KonTheCat 
Thanks for the feedback. This issue has finally been resolved - [Considerations](https://docs.microsoft.com/data-integration/gateway/service-gateway-onprem#considerations)
