### ISSUE TITLE
dotnet requirement in 19-09 gateway release not documented

### ISSUE THREAD

**Issue by rojomisin** [MicrosoftDocs/data-integration#7]
we pulled 19-09 release today and it now requires a dot net update, which is a reboot... which isn't documented as a requirement
<img width="426" alt="Screen Shot 2019-09-18 at 6 07 04 PM" src="https://user-images.githubusercontent.com/3313148/65209584-7adab000-da4d-11e9-9cc0-5cb5fd16c357.png">

**Comment by mgblythe** [comment]
Thanks for your comment, @rojomisin. I've assigned this issue for review.

**Comment by DougKlopfenstein** [comment]
@rojomisin Thanks for your feedback. The current minimum .NET framework requirement has been documented since Sept. 2019. I'm closing this issue as stale.
