### ISSUE TITLE
Data Gateway for accessing public internet anonymously?

### ISSUE THREAD

**Issue by MartinHBA** [MicrosoftDocs/data-integration#70]
guys, so... basically, if I have power bi report, that connects to public url as anonymous, I still need onprem data gateway??
srsly? When cloud Power BI is unable to collect public web itself, 
why don't you offer Data Gateway As a Service for accessing public websites?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c093e8d2-49bb-cf51-02a8-d7792913a5ad
* Version Independent ID: 8fe1e76c-37e2-c6a8-4667-6578164d5b1e
* Content: [On-premises data gateway FAQ](https://docs.microsoft.com/en-us/data-integration/gateway/service-gateway-onprem-faq)
* Content Source: [data-integration/gateway/service-gateway-onprem-faq.md](https://github.com/MicrosoftDocs/data-integration/blob/master/data-integration/gateway/service-gateway-onprem-faq.md)
* Product: **on-premises-data-gateway**
* Technology: ****
* GitHub Login: @arthiriyer
* Microsoft Alias: **arthii**

**Comment by DougKlopfenstein** [comment]
Hi @MartinHBA -
This seems to be product feedback or a request for product support rather than documentation feedback. For information about product feedback or customer support for gateways in Power BI, go to [Power BI Support](https://powerbi.microsoft.com/support/).
