### ISSUE TITLE
To connect to cloud data sources through a proxy we have updated the proxy in the following path "C:\Program Files\On-premises data gateway\m\Microsoft.Mashup.Container.NetFX45.exe.config." but after August month version upgrade this configured Mashup proxy has been replaced with empty file again.

### ISSUE THREAD

**Issue by sathishHM** [MicrosoftDocs/data-integration#71]
[Enter feedback here]

To connect to cloud data sources through a proxy we have updated the proxy in the following path "C:\Program Files\On-premises data gateway\m\Microsoft.Mashup.Container.NetFX45.exe.config." but after August month version upgrade this configured Mashup proxy has been replaced with empty file again.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac8472eb-e13f-bbb0-698c-8faa13701ad8
* Version Independent ID: f30533a4-65a0-85f9-bcb1-4c96b307cd76
* Content: [Configure proxy settings for the on-premises data gateway](https://docs.microsoft.com/en-us/data-integration/gateway/service-gateway-proxy)
* Content Source: [data-integration/gateway/service-gateway-proxy.md](https://github.com/MicrosoftDocs/data-integration/blob/master/data-integration/gateway/service-gateway-proxy.md)
* Product: **on-premises-data-gateway**
* Technology: ****
* GitHub Login: @arthiriyer
* Microsoft Alias: **arthii**

**Comment by DougKlopfenstein** [comment]
Hi @sathishHM -
The configure proxy settings article has been updated several times since you opened this issue. The text you note no longer appears in the article. I'm closing this issue as out of date, but if you feel that the article needs further updating, please reopen this issue.
