### ISSUE TITLE
Deprecated Azure Datacenter IP List url

### ISSUE THREAD

**Issue by Matusa69** [MicrosoftDocs/data-integration#72]
Hi All,
the link for the Azure Datacenter IP Address point to a deprecated website 
https://www.microsoft.com/download/details.aspx?id=41653 

please update the doc to point to correct url:
Azure IP Ranges and Service Tags – Public Cloud
https://www.microsoft.com/en-us/download/details.aspx?id=56519

Thx
andrea 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f4daef9a-341c-696a-1d19-de05ffd67588
* Version Independent ID: 7cd18c28-7227-488a-aa28-6b869058e715
* Content: [Adjust communication settings for the on-premises data gateway](https://docs.microsoft.com/en-us/data-integration/gateway/service-gateway-communication)
* Content Source: [data-integration/gateway/service-gateway-communication.md](https://github.com/MicrosoftDocs/data-integration/blob/master/data-integration/gateway/service-gateway-communication.md)
* Product: **on-premises-data-gateway**
* Technology: ****
* GitHub Login: @arthiriyer
* Microsoft Alias: **arthii**

**Comment by DougKlopfenstein** [comment]
Hi @Matusa69 -
Thanks for your feedback. This issue has been fixed.
