### ISSUE TITLE
Remove the documentation thats not relevant

### ISSUE THREAD

**Issue by mganeshphani** [MicrosoftDocs/data-integration#75]
Looks like we no longer have an option to change a region, please put in a clause if relays are the new way of doing it

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2a07eaa-023b-fbc8-9508-39411425d096
* Version Independent ID: efb6bb0e-5551-e2b3-4e98-3a34188600f3
* Content: [Set the datacenter region for the on-premises data gateway](https://docs.microsoft.com/en-us/data-integration/gateway/service-gateway-data-region)
* Content Source: [data-integration/gateway/service-gateway-data-region.md](https://github.com/MicrosoftDocs/data-integration/blob/master/data-integration/gateway/service-gateway-data-region.md)
* Product: **on-premises-data-gateway**
* Technology: ****
* GitHub Login: @arthiriyer
* Microsoft Alias: **arthii**

**Comment by JasonWHowell** [comment]
The option is there during installation I found, and is documented now. Closing this out as resolved. 
![image](https://user-images.githubusercontent.com/5067358/182533135-34d2dac4-b0cf-4295-b3d5-cdcfae60f707.png)
