### ISSUE TITLE
Provide more clarity on cluster-based deployments

### ISSUE THREAD

**Issue by mganeshphani** [MicrosoftDocs/data-integration#77]
If a data gateway is clustered with multiple machines, then how do we deal with the relay, can we use one WCF Relay for multiple machines? or each relay must be mapped to one machine only?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: abfcd58d-5bc6-93be-ca7f-3c8fef915c9b
* Version Independent ID: 61bc6d44-3dad-49d5-ef87-26b7b5b08604
* Content: [Set the Azure Relay for on-premises data gateway](https://docs.microsoft.com/en-us/data-integration/gateway/service-gateway-azure-relay)
* Content Source: [data-integration/gateway/service-gateway-azure-relay.md](https://github.com/MicrosoftDocs/data-integration/blob/master/data-integration/gateway/service-gateway-azure-relay.md)
* Product: **on-premises-data-gateway**
* Technology: ****
* GitHub Login: @arthiriyer
* Microsoft Alias: **arthii**

**Comment by DougKlopfenstein** [comment]
Hi @mganeshphani 
Thanks for your dedication to our documentation. Unfortunately, at this time we have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
