### ISSUE TITLE
documentation out of date

### ISSUE THREAD

**Issue by mganeshphani** [MicrosoftDocs/data-integration#79]
I no longer see the region selection option. this documentation is out of date
![image](https://user-images.githubusercontent.com/22988320/97896588-e7b91400-1cfa-11eb-9858-7ff41630cd27.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: abfcd58d-5bc6-93be-ca7f-3c8fef915c9b
* Version Independent ID: 61bc6d44-3dad-49d5-ef87-26b7b5b08604
* Content: [Set the Azure Relay for on-premises data gateway](https://docs.microsoft.com/en-us/data-integration/gateway/service-gateway-azure-relay)
* Content Source: [data-integration/gateway/service-gateway-azure-relay.md](https://github.com/MicrosoftDocs/data-integration/blob/master/data-integration/gateway/service-gateway-azure-relay.md)
* Product: **on-premises-data-gateway**
* Technology: ****
* GitHub Login: @arthiriyer
* Microsoft Alias: **arthii**

**Comment by DougKlopfenstein** [comment]
Hi @mganeshphani - 
Thanks for your feedback. The region selection option is currently just under the Recovery key text box, as shown in the current documentation.
