### ISSUE TITLE
"Remove or delete an on-premises data gateway" section is out of date

### ISSUE THREAD

**Issue by morgan-smith** [MicrosoftDocs/data-integration#85]
Need to update section on how to remove data gateway

https://docs.microsoft.com/en-us/data-integration/gateway/service-gateway-manage#remove-or-delete-an-on-premises-data-gateway

Had to refer to following URL for updated instructions:
https://www.fourmoo.com/2020/10/28/how-to-easily-remove-a-power-bi-on-premise-data-gateway-from-a-cluster/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 20180bfa-f4ab-224a-d089-58a06dbf4ac3
* Version Independent ID: f4ab3a3c-397d-01d1-f6d2-05e9085770a1
* Content: [Manage an on-premises data gateway](https://docs.microsoft.com/en-us/data-integration/gateway/service-gateway-manage)
* Content Source: [data-integration/gateway/service-gateway-manage.md](https://github.com/MicrosoftDocs/data-integration/blob/master/data-integration/gateway/service-gateway-manage.md)
* Product: **on-premises-data-gateway**
* Technology: ****
* GitHub Login: @arthiriyer
* Microsoft Alias: **arthii**

**Comment by DougKlopfenstein** [comment]
@morgan-smith 
Thanks for your feedback. The information on how to remove a data gateway has been moved to the appropriate application that's using the gateway. There are now two link on the page you reference above, one for Power BI and one for the Power Platform. Both of these links supply up to date information on how to remove a gateway from inside the Power BI service and the Power Platform admin center.
