### ISSUE TITLE
Containerised Docker Image for the Power Platform on-premises Data Gateway

### ISSUE THREAD

**Issue by haneef95** [MicrosoftDocs/data-integration#86]
Hi,

Is this Gateway available as a Docker Image?

It'll be very useful in the scenario where the on-premises data endpoints are on Linux or running on Docker Containers

Thanks,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c51a10c-d90c-7690-0979-cd8ce37234c8
* Version Independent ID: 2da65f4c-f128-40b8-1a2b-5ae72c4252d6
* Content: [Install an on-premises data gateway](https://docs.microsoft.com/en-us/data-integration/gateway/service-gateway-install)
* Content Source: [data-integration/gateway/service-gateway-install.md](https://github.com/MicrosoftDocs/data-integration/blob/master/data-integration/gateway/service-gateway-install.md)
* Product: **on-premises-data-gateway**
* Technology: ****
* GitHub Login: @arthiriyer
* Microsoft Alias: **arthii**

**Comment by zebrassimo** [comment]
It would be really great if we could run the gateway in an azure container connected to the on-premise infrastructure.

**Comment by mganeshphani** [comment]
i have been dreaming of it since 3 -4 years and raised in multiple forums with Microsoft, i am guessing that is not the path they are taking forward

**Comment by acds** [comment]
@zebrassimo & @zebrassimo @haneef95  et al - the Azure Container Instance can run Windows containers - so embracing linux is a red herring.

Seems like it's possible with what [Synapse Integration Runtime](https://docs.microsoft.com/en-us/azure/data-factory/how-to-run-self-hosted-integration-runtime-in-windows-container) to solve it's equivalent of the same problem. 

Per `Docker` [file](https://github.com/Azure/Azure-Data-Factory-Integration-Runtime-in-Windows-Container/blob/ec3be1746dda2436ff2e7a00e500416ac878d276/Dockerfile) - this runs on `mcr.microsoft.com/windows/servercore:ltsc2019`. 

The question then to MS would then be _"Is the same or similar setup approach possible with the Power BI Gateway?"_

**Comment by haneef95** [comment]
> Porting to dotnetcore will need to be done

It's already done it seems: https://devblogs.microsoft.com/dotnet/azure-active-directorys-gateway-is-on-net-6-0/

They leap has also been made from `IIS` to `HTTP.sys`. Just need to give the users the option to use `Kestrel`, to tap into it's cross-platform-abliity.

**Comment by haneef95** [comment]
@acds - Thanks. But, looking for Microsoft's officially supported image for this purpose.

**Comment by haneef95** [comment]
Any updates on this?

**Comment by DougKlopfenstein** [comment]
Hi @haneef95 
Thanks for your dedication to our documentation. Unfortunately, at this time we have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. Though the scope of our feedback channel here on GitHub covers specific documentation fixes, we can help redirect you to the right support channel to get an answer to your question: [Power users community forum](https://powerusers.microsoft.com/#forum_discussions). Because this issue does not relate to documentation, we are closing this issue.
