### ISSUE TITLE
Page update frequency

### ISSUE THREAD

**Issue by mauledbyjesus** [MicrosoftDocs/data-integration#94]
Is it possible to sync the update of this page with new releases of the product? I've got customers asking how they can know when a new version is released and right this second, I can't suggest monitoring this page and I'm not sure why there is a list of previous updates. Is that a standard format, just showing previous vs a list of ALL?

Update: I'm having them follow the "on-premises data gateway" tag on the PBI blog, but something official would be nice.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 27fa3259-c8cf-bd35-7e6a-6f8a1f2a36cf
* Version Independent ID: 187906ab-5531-bce0-084c-d90e3c009c82
* Content: [Previous monthly updates to the on-premises data gateways](https://docs.microsoft.com/en-us/data-integration/gateway/service-gateway-monthly-updates?source=docs)
* Content Source: [data-integration/gateway/service-gateway-monthly-updates.md](https://github.com/MicrosoftDocs/data-integration/blob/master/data-integration/gateway/service-gateway-monthly-updates.md)
* Product: **on-premises-data-gateway**
* Technology: ****
* GitHub Login: @arthiriyer
* Microsoft Alias: **arthii**

**Comment by JasonWHowell** [comment]
Unfortunately, the docs site doesn't have a great "What's new" automated solution. Many have asked for it, and the idea is great.  RSS feeds are possible, but not very good in practice.
