### ISSUE TITLE
Explanation should be more precise about which gateway each sentence is talking about

### ISSUE THREAD

**Issue by dbz78** [MicrosoftDocs/data-integration#96]
[Enter feedback here]
Explanation text is not clear. Which gateway is considered should be easier to understand.
List of steps should read:

_1. The cloud service creates a query and the encrypted credentials for the on-premises data source. The query and credentials are sent to the gateway **CLOUD SERVICE'S** queue for processing. For more information about credential encryption in Power BI, see Power BI security whitepaper.
2. The gateway cloud service analyzes the query and pushes the request to Azure Service Bus Messaging.
3. Azure Service Bus sends the pending requests to the **ON-PREMISES** gateway.
4. The **ON-PREMISES** gateway gets the query, decrypts the credentials, and connects to one or more data sources with those credentials.
5. The **ON-PREMISES** gateway sends the query to the data source to be run.
6. The results are sent from the data source back to the **ON-PREMISES** gateway and then to the cloud service. The service then uses the results.
7._ 

Thanks,
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c654ef3-6a36-2f86-9640-1585efabfd0a
* Version Independent ID: 2c3c6a6a-d095-f057-b225-dc1206b2d72a
* Content: [On-premises data gateway architecture](https://docs.microsoft.com/en-us/data-integration/gateway/service-gateway-onprem-indepth)
* Content Source: [data-integration/gateway/service-gateway-onprem-indepth.md](https://github.com/MicrosoftDocs/data-integration/blob/master/data-integration/gateway/service-gateway-onprem-indepth.md)
* Product: **on-premises-data-gateway**
* Technology: ****
* GitHub Login: @arthiriyer
* Microsoft Alias: **arthii**

**Comment by JasonWHowell** [comment]
@DougKlopfenstein seems like a few keywords would clarify the steps as suggested.

**Comment by jonburchel** [comment]
Thanks @dbz78 for your dedication to our documentation. Unfortunately, at this time we have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. The requested updates have not been made since the creation of this issue, and the timeline for resolution may vary based on resourcing, so we've created an internal work item to incorporate your suggestions. We are closing this issue for now, but feel free to comment here as necessary. #please-close
