### ISSUE TITLE
Update Outbound Ports based on requirements for HTTPS or TCP

### ISSUE THREAD

**Issue by olyamusok** [MicrosoftDocs/data-integration#97]
Update FQDNs list to be more clear related to what ports need to be open based on HTTPS or TCP modes
Suggestion: 
Replace this:

Public Cloud Domain names | Outbound ports | Description
-- | -- | --
*.download.microsoft.com | 80 | Used to download the installer. The gateway app also uses this domain to check the version and gateway region.
*.powerbi.com | 443 | Used to identify the relevant Power BI cluster.
*.analysis.windows.net | 443 | Used to identify the relevant Power BI cluster.
*.login.windows.net, login.live.com, and aadcdn.msauth.net | 443 | Used to authenticate the gateway app for Azure Active Directory (Azure AD) and OAuth2.
*.servicebus.windows.net | 5671-5672 | Used for Advanced Message Queuing Protocol (AMQP).
*.servicebus.windows.net | 443 and 9350-9354 | Listens on Service Bus Relay over TCP. Port 443 is required to get Azure Access Control tokens.
*.frontend.clouddatahub.net | 443 | Deprecated and not required. This domain will be removed from the public documentation as well.
*.core.windows.net | 443 | Used by dataflows to write data to Azure Data Lake.
login.microsoftonline.com | 443 | Used to authenticate the gateway app for Azure AD and OAuth2.
*.msftncsi.com | 443 | Used to test internet connectivity if the Power BI service can't reach the gateway.
*.microsoftonline-p.com | 443 | Used to authenticate the gateway app for Azure AD and OAuth2.
*.dc.services.visualstudio.com | 443 | Used by AppInsights to collect telemetry.

With this while also removing the deprecated one. It took a lot of testing and emails to Microsoft support to confirm that only ports required if working in default HTTPs mode are 443 and 80. This is really needed to help clients with extensive on-prem network security initial firewall configuration. 

Public   Cloud Domain names | Outbound ports (Default HTTPS) | Outbound Ports ( TCP) | Description
-- | -- | -- | --
*.download.microsoft.com | 80 | 80 | Used to   download the installer. The gateway app also uses this domain to check the   version and gateway region.
*.powerbi.com | 443 | 443 | Used to   identify the relevant Power BI cluster.
*.analysis.windows.net | 433 | 443 | Used to   identify the relevant Power BI cluster.
*.login.windows.net, login.live.com, and   aadcdn.msauth.net | 433 | 443 | Used to   authenticate the gateway app for Azure Active Directory (Azure AD) and   OAuth2.
*.servicebus.windows.net | 443 | 5671-5672 | Used for   Advanced Message Queuing Protocol (AMQP).
*.servicebus.windows.net | 443 | 443 and   9350-9354 | Listens   on Service Bus Relay over TCP. Port 443 is required to get Azure Access   Control tokens.
*.core.windows.net | 443 | 443 | Used by   dataflows to write data to Azure Data Lake.
login.microsoftonline.com | 443 | 443 | Used to   authenticate the gateway app for Azure AD and OAuth2.
*.msftncsi.com | 443 | 443 | Used to   test internet connectivity if the Power BI service can't reach the gateway.
*.microsoftonline-p.com | 443 | 443 | Used to   authenticate the gateway app for Azure AD and OAuth2.
*.dc.services.visualstudio.com | 443 | 443 | Used by   AppInsights to collect telemetry.

Thank you
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f4daef9a-341c-696a-1d19-de05ffd67588
* Version Independent ID: 7cd18c28-7227-488a-aa28-6b869058e715
* Content: [Adjust communication settings for the on-premises data gateway](https://docs.microsoft.com/en-us/data-integration/gateway/service-gateway-communication)
* Content Source: [data-integration/gateway/service-gateway-communication.md](https://github.com/MicrosoftDocs/data-integration/blob/master/data-integration/gateway/service-gateway-communication.md)
* Product: **on-premises-data-gateway**
* Technology: ****
* GitHub Login: @arthiriyer
* Microsoft Alias: **arthii**

**Comment by czajek** [comment]
This PR seems to be very valuable and I was looking for this information for quite a while. It's sad it's still open. It should be super clear what firewall rules need to be applied and current documentation is confusing.

**Comment by jonburchel** [comment]
Thanks @olyamusok for your dedication to our documentation. Unfortunately, at this time we have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. The requested updates have not been made since the creation of this issue, and the timeline for resolution may vary based on resourcing, so we've created an internal work item to incorporate your suggestions. We are closing this issue for now, but feel free to comment here as necessary. #please-close
